### ISSUE TITLE
issue about FIR framework

### ISSUE THREAD

**Issue by zeeshan083** [certsocietegenerale/FIR#100]
sir tell me that the Django Rest framework is used in FIR or not. if used and where it is used?
or its totally build on Djngo Framework....
Thanks

**Comment by byt3smith** [comment]
It is used in the fir_api plugin

**Comment by byt3smith** [comment]
this issue can be closed, I believe, as a non-issue

**Comment by tomchop** [comment]
Yes, thanks!
