### ISSUE TITLE
Unable to create /FIR/run/* directory

### ISSUE THREAD

**Issue by lipeviveros** [certsocietegenerale/FIR#101]
Hi,

which adjustments should I make to run FIR. I am using python virtual env:

error message I get when I run FIR:

**$start fir
start: Rejected send message, 1 matched rules; type="method_call", sender=":1.10" (uid=1000 pid=11152 comm="start fir ") interface="com.ubuntu.Upstart0_6.Job" member="Start" error name="(unset)" requested_reply="0" destination="com.ubuntu.Upstart" (uid=0 pid=1 comm="/sbin/init")
**

please help.

**Comment by tomchop** [comment]
Sounds like you have a problem with your upstart script. Have you tried launching FIR in dev mode?

**Comment by tomchop** [comment]
Closed due to inactivity. Please re-open this issue if you're still having trouble.
