### ISSUE TITLE
Extend artifact tooltips with additional services (e.g. OTX)

### ISSUE THREAD

**Issue by mthlvt** [certsocietegenerale/FIR#103]
Let's say I want to add another tooltip to search for an artifact on another service than centralops or VT, for example on Open Threat Exchange.

I understood the related code is here `FIR/fir_artifacts/static/fir_artifacts/js/tooltips.js` but instead of writing a _quick and dirty_ hack, what would be a better way to add a tooltip with OTX instead/along centralops/VT tooltips? 

Is it  better to modify the artifact plugin or build another plugin? Any ideas?

example of OTX urls: https://otx.alienvault.com/indicator/ip/1.2.3.4
or via the api: https://otx.alienvault.com/api/v1/indicators/ip/1.2.3.4/reputation (with api key)

finally there's a python sdk for OTX https://github.com/AlienVault-Labs/OTX-Python-SDK

**Comment by tomchop** [comment]
I think this definitely deserves a plugin.

- You might end-up having to manage credentials / API tokens / etc. for accessing your services, which would ideally be configured at the database level and not hardcoded in the plugins themselves
- If you keep a big list of services in the tooltip, the UI will get ugly real quick. Maybe a separate tab for artifact "analysis" would be better suited?

**Comment by mthlvt** [comment]
Thanks, I read the [wiki](https://github.com/certsocietegenerale/FIR/wiki/Plugins) page about plugins but it doesn't say much about writing your own plugin.

Any advice?

**Comment by mthIvt** [comment]
Since time, my problem is solved.
Thanks
