### ISSUE TITLE
Add a "Related Incidents" relationship

### ISSUE THREAD

**Issue by dcode** [certsocietegenerale/FIR#106]
The incident object should have a ManytoMany relationship to other instances of the model. This is to fit the use-case of multiple incident investigations are being performed in parallel and they end up being the same, or possibly multiple campaigns by the same actor over time. This allows better long term analysis and a close relationship with more robust knowledge management/analytic platforms like CRITs or other STIX-compatible data models.

See http://stixproject.github.io/data-model/1.2/incident/IncidentType/ for the STIX schema. In that schema, they actually recommend (for the XML rendered relationship) a FK relationship to a "RelatedIncidents" object that includes additional metadata such as relationship type, confidence, etc. That might be too complex for the level of effort. If a relationship is made, a comment can be added to the incident to explain why that was made.

**Comment by tomchop** [comment]
The only way to currently link incidents between them is via the artifacts (or observables in STIX terminology). We probably won't add a many-to-many relationship between incidents just yet, but we're thinking of adding a special type of artifact what can be used to manually link incidents together.

**Comment by tomchop** [comment]
Implemented in @gcrahay's pull request. Thanks!

**Comment by josarsepi** [comment]
gcrahay, any chance we can get an example of what:

"Markdown rendering with incident # parsing and linking" expounded upon in the documentation?

**Comment by gcrahay** [comment]
Something got broken when merging that feature. I'll investigate and submit a PR to fix it.

**Comment by gcrahay** [comment]
OK, no need to submit a PR. @tomchop changed the incident link regex when merging. You should write `FID:<incident number>` to create a link to an incident in incident descriptions and comments.

**Comment by josarsepi** [comment]
Awesome,  I am glad the feature was added but was having issues finding details on how to use it.  Our team had asked me about nesting or relating tickets prior to the update.  Thanks for the info.

**Comment by gcrahay** [comment]
There's also a new core plugin named `fir_relations`. If you add it in your `installed_apps.txt` and do a `./manage.py migrate`, related incidents will be shown on the incident details sidebar.

The plugins parses incident description and comment on save signal, so old relations will not be shown (edit and save the description and/or comment to force parsing).

**Comment by josarsepi** [comment]
gcrahay,
Thanks for taking the time to develop this plugin.  I made the change to my installed_apps.txt today and really like it.  It's a big improvement.
