### ISSUE TITLE
Trying to configure SMTP alerting using google gmail

### ISSUE THREAD

**Issue by PingRIvis** [certsocietegenerale/FIR#107]
We use Gmail for our messaging system. Any hints or links to a document that can expose more SMTP settings besides EMAIL_HOST and EMAIL_PORT ? Thanks!

**Comment by tomchop** [comment]
We use Django's native libraries to manage our SMTP connections. If you configure FIR to go through gmail's SMTP servers, I think you should be fine.

Django's documentation: We use Django's native libraries to manage our SMTP connections: https://docs.djangoproject.com/en/1.9/topics/email/
This might be of help for setting up gmail's SMTP servers: https://www.digitalocean.com/community/tutorials/how-to-use-google-s-smtp-server

**Comment by ankitsultania** [comment]
@PingRIvis : Hello, were you able to configure this?
