### ISSUE TITLE
Cannot create new event / incident

### ISSUE THREAD

**Issue by alexurbanowicz** [certsocietegenerale/FIR#109]
Environment: freshly downloaded FIR in devel setup witout plugins installed (same effect when reinstalled with plugins). Debian 7.11.

I log in as admin, click "New event", fill up the form, click Save and unbound "Please fill in this field" appears on the screen. The incident is not created. I cannot get past the first screen.

![fir](https://cloud.githubusercontent.com/assets/2536209/16655485/d31e303e-445a-11e6-8b9e-7516b85a425c.png)

**Comment by tomchop** [comment]
That's strange, it looks like some kind of HTML5 validation (which we don't use in our code). Have you tried doing the same thing with another browser?

**Comment by alexurbanowicz** [comment]
This was Firefox / Iceweasel. On Chromium there is no validation notification but "Save" still does nothing.

**Comment by tomchop** [comment]
Can you run `$ pip freeze` and paste the output here please?

**Comment by alexurbanowicz** [comment]
```
Django==1.10b1
Markdown==2.6.6
argparse==1.2.1
cssselect==0.9.1
distribute==0.6.24
django-filter==0.13.0
djangorestframework==3.3.3
flup==1.0.2
lxml==3.4.2
pymongo==2.8
pyquery==1.2.9
python-dateutil==2.4.1
pytz==2014.10
six==1.9.0
wsgiref==0.1.2
```

**Comment by tomchop** [comment]
I see some discrepancies - your version of Django seems to be pretty recent. Can you try installing `django==1.9.1` and see if that fixes anything?

**Comment by alexurbanowicz** [comment]
Yes it does.

**Comment by tomchop** [comment]
Awesome. Thanks for your time. We'll fix the requirements so that beta versions aren't installed in the future.
