### ISSUE TITLE
Unable to run FIR in production

### ISSUE THREAD

**Issue by seifreed** [certsocietegenerale/FIR#110]
Hi,

I tried to install FIR un production, I tried to use upstart, but seems not compatible with the last Ubuntu distribution

> start: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused

Any thoughts?

**Comment by tomchop** [comment]
Yes, `upstart` is not installed by default in the latest Ubuntu distros. They use `systemd`: https://wiki.ubuntu.com/SystemdForUpstartUsers. We need to update the documentation to reflect this.

**Comment by seifreed** [comment]
You have any example about a systemd config?

**Comment by myntric** [comment]
Here is a copy of my daemon configuration.

/etc/systemd/system/uwsgi.service

[Unit]
Description=uWSGI instance to serve myapp
After=syslog.target

[Service]
User=nginx
Group=nginx
WorkingDirectory=/opt/FIR/run
ExecStart=/usr/bin/uwsgi --socket /opt/FIR/run/fir.sock --chdir /opt/FIR/ --module fir.wsgi
Restart=always
KillSignal=SIGQUIT
Type=Debug
StandardError=syslog
NotifyAccess=All

[Install]
WantedBy=multi-user.target

**Comment by tomchop** [comment]
Any updates on this @seifreed ?

**Comment by cameldelamotto** [comment]
Hi,

I have the same issue.
When will the documentation be update?

**Comment by tomchop** [comment]
The documentation has been [updated](https://github.com/certsocietegenerale/FIR/wiki/Installation-on-a-production-environment#uwsgi)
