### ISSUE TITLE
Install Issue - Create Tables in Database Failure

### ISSUE THREAD

**Issue by shaigb** [certsocietegenerale/FIR#111]
Hi

I'm trying to install on virtual Env, and when trying to create the tables in the DB I get an error:

(env-FIR) sansforensics@siftworkstation:~/FIR$ ./manage.py migrate --settings fir.config.production
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management

Any Ideas ?

**Comment by tomchop** [comment]
What version of Django are you running?

**Comment by cameldelamotto** [comment]
I have the same issue with django 1.10.0

**Comment by tomchop** [comment]
Do you run into the same issue if you downgrade your Django version to 1.9.1?

**Comment by infracritical** [comment]
I ran into this issue whilst I was using 'virtualenv'.  Once I escaped out, and utilized the current Python modules, for me, it worked.  BTW, I am running Ubuntu 14.04.5.

**Comment by tomchop** [comment]
@shaigb and @cameldelamotto, did this fix your issue?

**Comment by gaelmuller** [comment]
Closing this because it is old. If you are still having this issue, you could try installing requirements:

````
pip install -r requirements.txt
````

Do not hesitate to reopen if this is still an issue.
