### ISSUE TITLE
Unable to authenticate into FIR using JAVA progarm

### ISSUE THREAD

**Issue by mhaydox** [certsocietegenerale/FIR#114]
Hi everyone, I am having truble with authentication into the FIR application using JAVA program. Here is some explinations:
1) the JAVA program that I am using allow me to authenticate to other applications such as QRadar.
2) I'm able to authenticate into the FIR application using my Browser.
3) I am getting this error : Failed : HTTP error code : 401
4) this is the code I am using It works 100%  with other applications (I am ignoring SSL verification) :

try {

			URL url = new URL(
					"https://localhost/api/");
			HttpURLConnection conn = (HttpURLConnection) url.openConnection();
			String userpass = username + ":" + password;
            String basicAuth = "Basic " + new sun.misc.BASE64Encoder().encode(userpass.getBytes());
            conn.setRequestProperty ("Authorization", basicAuth);
			conn.setRequestMethod("GET");
			conn.setRequestProperty("Accept", "application/json");

			if (conn.getResponseCode() != 200) {
				throw new RuntimeException("Failed : HTTP error code : " + conn.getResponseCode());
			}

			BufferedReader br = new BufferedReader(new InputStreamReader(
					(conn.getInputStream())));

			String output;
			System.out.println("Output from Server .... \n");
			while ((output = br.readLine()) != null) {

				System.out.println(output);
			}
			
			conn.disconnect();

		} catch (MalformedURLException e) {

			e.printStackTrace();
		} catch (IOException e) {

			e.printStackTrace();
			
		}

	}

**Comment by weslambert** [comment]
Have you declared the username and password as strings?

Ex.  
String username = "user1";
      String password = "thisismypassword"; 

Thanks,
Wes

**Comment by tomchop** [comment]
It seems you're using Basic Auth to authenticate, which is usually specified at a werbserver level rather than an application level.

FIR does not use Basic Auth, instead it uses a specific authentication mechanism. Check out [this pull request](https://github.com/certsocietegenerale/FIR/pull/43) for more information on how to authenticate your API for querying FIR programmatically. (we still need to get this documented)

**Comment by mhaydox** [comment]
thank you weslambert for your help .yes I am using declared usename and
password variables .

2016-08-24 16:46 GMT+01:00 weslambert <notifications@github.com>:
