### ISSUE TITLE
FIR GitHub Organization

### ISSUE THREAD

**Issue by byt3smith** [certsocietegenerale/FIR#117]
Hey guys,

Just wanted to raise the notion of making a Fast Incident Response organization here on GitHub. That way, we could add things like API client code, REST API documentation, community-developed plugins, etc. without modifying the main repository.

**Comment by weslambert** [comment]
I second this notion. :)

**Comment by infracritical** [comment]
Third.

**Comment by eth-0** [comment]
Fourth

**Comment by tomchop** [comment]
This is interesting! We'll consider it and see what's the best way to get it set up.
