### ISSUE TITLE
Securing "nginx" with SSL (using Let's Encrypt)

### ISSUE THREAD

**Issue by infracritical** [certsocietegenerale/FIR#118]
I am a longtime Apache user and developer, and have never really used "nginx" before (though I am not opposed to using it).  I am trying to secure the web connection by using EFF's "Let's Encrypt" encryption process.

Has anyone attempted this?  If so, could you post how you did it?  TIA.

**Comment by weslambert** [comment]
Have you seen the following?

https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-14-04
https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04

Thanks,
Wes

**Comment by infracritical** [comment]
I wasn't entirely certain how this would transpire, and not being entirely familiar with 'nginx' didn't help, either.  However, having worked with other 'flavours' of LINUX, I am used to working with more obstinate versions, and as such, am used to performing more (ahem) 'manual' steps.  Working with Ubuntu has been rather refreshing of the 'drop it, and fahgit-ah-bout-it'.

For those who may similar issues, this is what ended up being my modified 'nginx' configuration file (under "**/etc/nginx/site-defaults/fir**":

**upstream fir {
    server unix://$FIRDIR/fir.sock;
}

server {
    listen 80;
    server_name XXXXXX;
    return 301 https://$host$request_uri;
}

server {
    server_name XXXXXX;

    location / {
        uwsgi_pass fir;
        include $FIRDIR/uwsgi_params;
    }

    location /static/ {
        alias $FIRDIR/static/;
    }

    location ~ /.well-known {
        allow all;
    }

    listen 443 ssl;

    ssl_certificate /etc/letsencrypt/live/XXXXXX/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/XXXXXX/privkey.pem;
}**
