### ISSUE TITLE
Add Ticket/Incident/Event Numbers 

### ISSUE THREAD

**Issue by weslambert** [certsocietegenerale/FIR#120]
I think it would be nice to have a ticket/event/incident number generated each time a new entry is created.  May this already available and I am missing it?

Thanks,
Wes

**Comment by eth-0** [comment]
Each event/incident has an ID number. They can been seen via the api at `/api/incidents`. Does that fulfill your need, or did you want it displayed via the web UI?

**Comment by weslambert** [comment]
It would be awesome if we could display in the web  UI, so that one analyst
could refer another analyst to the event ID, etc.

Thanks!
Wes

**Comment by gcrahay** [comment]
Hi,

The feature has been requested in #14 and #18.

You can add this setting to display the incident ID in the Web UI:
```
INCIDENT_SHOW_ID = True
```

**Comment by weslambert** [comment]
Whoops, I apologize for my negligence.

I'll close this one.  Thanks!
