### ISSUE TITLE
Adding text-only field?

### ISSUE THREAD

**Issue by infracritical** [certsocietegenerale/FIR#121]
Part of the reporting that I would like is to create text-edit/text-only fields that are free-flowing; that is, create one or more fields that allow me to enter various text based on the field's role.  For example, I would want a field that requests, "Specify Operation Description", then another field requesting, "Operation Duration", followed by another field requesting, "Operation Recovery Method" (outlining what methods were used to recover from the occurrence/event/incident.  I have a requirement for what we're doing to have this free-flowing text-edit/text-only fields.  Is this something that currently exists?  And if not, would this be possible?

**Comment by gaelmuller** [comment]
You have two options:

- Use attributes (https://github.com/certsocietegenerale/FIR/wiki/Attributes) without setting a unit. This will allow you to put text as an attribute value. Be aware that attributes were not made for this, so this could feel hackish.
- Write a plugin (https://github.com/certsocietegenerale/FIR/wiki/Plugins)
