### ISSUE TITLE
Occurrence type?

### ISSUE THREAD

**Issue by infracritical** [certsocietegenerale/FIR#122]
There is a checkbox that has it as "Is this an incident?", with another one indicating, "Is this incident major?"  Within our community, there are varying levels of 'incidents': "occurrence", "event", "situation" and "incident".  The term "incident" bears legal ramifications; meaning, if it were treated as an "incident", that this is a reportable occurrence which would require substantial paperwork be filled out.  Also, a separate checkbox indicating if the incident is covered by  a regulation, if so, which regulatory agency would require the reporting, what section(s) (one or more in many circumstances), along with the regulation name.

**Comment by gaelmuller** [comment]
I did not really get your question here. In FIR, you can only differenciate between Events and Incidents.

If you want to be more specific, you would have to use one of the following techniques:

  - Use the Incident Severity levels
  - Have a convention linking specific incident categories to your different level of incidents
  - Use Attributes (https://github.com/certsocietegenerale/FIR/wiki/Attributes), for example an attribute "situation" that you would set to "1"
  - Write a plugin (https://github.com/certsocietegenerale/FIR/wiki/Plugins)
