### ISSUE TITLE
Creating multiple date/time fields?

### ISSUE THREAD

**Issue by infracritical** [certsocietegenerale/FIR#124]
Need to create multiple date and time fields; for instance, date/time of the occurrence, date/time of duration of the occurrence, date/time of when the operation became available, duration of recovery time before the operation became available, date/time of reporting the occurrence to the regulatory agency, date/time of the arrest (if criminal), date/time of court hearing (if criminal), date/time of sentencing (if criminal), etc.

**Comment by gaelmuller** [comment]
Here is what we do to track the different datetimes associated with an event:

- When creating an incident, we set the datetime field to the datetime of occurence.
- For every other datetime that we want to store, we use comments. For example, if you want to store the datetime of a criminal arrest, you would write a comment "Criminal X arrested" and set the datetime to match the one of the arrest. This will get you a nice timeline of the incident in the comments.

If you feel this doesn't answer your question well enough, there is always the possibility of writing a plugin (https://github.com/certsocietegenerale/FIR/wiki/Plugins).
