### ISSUE TITLE
Unable to delete an event

### ISSUE THREAD

**Issue by infracritical** [certsocietegenerale/FIR#126]
If I made an error and decided to close the occurrence/event/incident, I *cannot* delete that entry.  

How do I do this??!!??  If there is no option to remove an occurrence/event/incident, this *needs* to be a new feature.

**Comment by gaelmuller** [comment]
You can delete an event / incident using the administration panel. To access the panel, log in with an administrative account (you should have created one) and go to YOURFIRURL/admin or click on [Admin] in the top right corner.

**Comment by infracritical** [comment]
This isn't an obvious process.  Yes, I have to go to the administrative panel, but I didn't realize that I had to click on "Incidents" to view the currently identified events/incidents are there.  This is an implied function of the application.
