### ISSUE TITLE
wsgi.py settings module name

### ISSUE THREAD

**Issue by Blacksyke** [certsocietegenerale/FIR#128]
Commit 04dbefcf44b0e8433f5894aa31926065b12c6b7b changed the name of the settings module in fir/wsgi.py, and this change broke a production install (uwsgi fails to initialize the application). Reverting "fir.settings" back to "fir.config.production" fixed it. What's up with that? I notice this change has been made and reverted in the past.

**Comment by tomchop** [comment]
We merged 04dbefc too quickly, sorry about that. We're going to revert the changes in the file.
