### ISSUE TITLE
Trying to set up development environment: ValueError at /admin/login/

### ISSUE THREAD

**Issue by CJOak** [certsocietegenerale/FIR#130]
Hi. So, I'm trying to set up FIR through Apache (it has mod_wsgi), but I get the debug page about ValueError when I press "Sign in" for the FIR page as well as for the Django administration login page (I tried 'admin' as both username and password). I followed the instructions on https://github.com/certsocietegenerale/FIR/wiki/Setting-up-a-development-environment up until './manage.py runserver', as I assume that wouldn't be helpful if I'm trying to run it through Apache (I also didn't do the two apt-gets at the beginning; the system is running RedHat).

The three changes I recall making are 
1) copying Django's admin directory containing static files into fir/incidents/static/ so that they would be served when I went to domain.com/admin ,
2) changing the time zone in base.py to 'America/New_York', and
3) changing fir.config.production in fir/wsgi.py to fir.settings .

The debug page says 'ValueError at /admin/login/' with 'unknown reasons' beneath it. The exception location is '.../python2.7/site-packages/django/utils/crypto.py in pbkdf2, line 139', which says <code>return hashlib.pbkdf2_hmac(digest().name, password, salt, iterations, dklen)</code> . I don't know what information would be relevant.

It is entirely possible I have no idea what I'm doing (though the system is also a bit odd), but any help you can offer would be appreciated.

**Comment by tomchop** [comment]
Hi. Can you please print the full stack trace that you see? 

We also recommend using the [production instructions](https://github.com/certsocietegenerale/FIR/wiki/Installation-on-a-production-environment) (which also explain how to properly serve static files) if you want to use a proper webserver (such as Apache) to serve the app. We included instructions only for nginx but the setup for Apache should be fairly similar.

**Comment by CJOak** [comment]
<details>
<summary>Traceback</summary>
Environment:


Request Method: POST
Request URL: https://[sitename]/admin/login/?next=/admin/

Django Version: 1.9.9
Python Version: 2.7.12
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'incidents',
 'django.contrib.admin',
 'rest_framework',
 'rest_framework.authtoken',
 'fir_plugins',
 'fir_artifacts',
 'fir_alerting',
 'fir_todos',
 'fir_nuggets',
 'fir_api')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware')



Traceback:

File "/export/software/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
149.                     response = self.process_exception_by_middleware(e, request)

File "/export/software/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/export/software/lib/python2.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
57.         response = view_func(request, *args, **kwargs)

File "/export/software/lib/python2.7/site-packages/django/contrib/admin/sites.py" in login
414.         return login(request, **defaults)

File "/export/software/lib/python2.7/site-packages/django/contrib/auth/views.py" in inner
49.         return func(*args, **kwargs)

File "/export/software/lib/python2.7/site-packages/django/views/decorators/debug.py" in sensitive_post_parameters_wrapper
76.             return view(request, *args, **kwargs)

File "/export/software/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapped_view
149.                     response = view_func(request, *args, **kwargs)

File "/export/software/lib/python2.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
57.         response = view_func(request, *args, **kwargs)

File "/export/software/lib/python2.7/site-packages/django/contrib/auth/views.py" in login
69.         if form.is_valid():

File "/export/software/lib/python2.7/site-packages/django/forms/forms.py" in is_valid
161.         return self.is_bound and not self.errors

File "/export/software/lib/python2.7/site-packages/django/forms/forms.py" in errors
153.             self.full_clean()

File "/export/software/lib/python2.7/site-packages/django/forms/forms.py" in full_clean
363.         self._clean_form()

File "/export/software/lib/python2.7/site-packages/django/forms/forms.py" in _clean_form
390.             cleaned_data = self.clean()

File "/export/software/lib/python2.7/site-packages/django/contrib/auth/forms.py" in clean
161.                                            password=password)

File "/export/software/lib/python2.7/site-packages/django/contrib/auth/__init__.py" in authenticate
74.             user = backend.authenticate(**credentials)

File "/export/software/lib/python2.7/site-packages/django/contrib/auth/backends.py" in authenticate
18.             if user.check_password(password):

File "/export/software/lib/python2.7/site-packages/django/contrib/auth/base_user.py" in check_password
110.         return check_password(raw_password, self.password, setter)

File "/export/software/lib/python2.7/site-packages/django/contrib/auth/hashers.py" in check_password
52.     is_correct = hasher.verify(password, encoded)

File "/export/software/lib/python2.7/site-packages/django/contrib/auth/hashers.py" in verify
265.         encoded_2 = self.encode(password, salt, int(iterations))

File "/export/software/lib/python2.7/site-packages/django/contrib/auth/hashers.py" in encode
258.         hash = pbkdf2(password, salt, iterations, digest=self.digest)

File "/export/software/lib/python2.7/site-packages/django/utils/crypto.py" in pbkdf2
139.         return hashlib.pbkdf2_hmac(digest().name, password, salt, iterations, dklen)

Exception Type: ValueError at /admin/login/
Exception Value: unknown reasons
</details>

If/when I do end up following the instructions for production, I would like a few clarifications first that I hope you can answer. 
1) Since I'm using Apache, would I have to use mod_uwsgi instead of uwsgi?
2) Will I be able to at least get past the login screen without configuring a MySQL database?
3) Partly related to question 1, I noticed that for `exec uwsgi --socket /path/to/your/FIR/install/run/fir.sock --chdir /path/to/your/FIR/install/ --module fir.wsgi`, the documentation says "The exec line must be adjusted if you're using a Python virtual environment," but it doesn't explicitly say how it has to be adjusted. I can probably figure it once I actually get there, but I would prefer to know exactly what I should adjust.

**Comment by tomchop** [comment]
1) I don't know how to set up Django with Apache ([this](https://docs.djangoproject.com/en/1.10/howto/deployment/wsgi/modwsgi/) can probably help).
2) No, you'll need to have at least one user available. But you can change the DB engine in your settings.py file to use sqlite if you don't want to be running a full RDBMS
3) You need to call `uwsgi` from your python virtual environment. You can also probably do `source /path_to_virtualenv/bin/activate; uwsgi --socket [...]`

Hope this helps

**Comment by CJOak** [comment]
Thanks.

I haven't quite reached that point yet, but I do now have MySQL running. I'm now stuck at `./manage.py migrate --settings fir.config.production`, though, because MySQL is running on a different socket than what I assume is standard. I am not familiar with `manage.py`, but I don't seem to be able to do something like --socket=x with that command. Is there someplace I can specify what socket `manage.py` tries to use?

**Comment by tomchop** [comment]
Good. Closing the issue if everything works for you.

**Comment by CJOak** [comment]
I tried a few things first, but unfortunately, no, it still is not working. Despite following all the instructions on the production page (besides nginx and uwsgi related ones; I swapped www-data with httpd as that seems to be what Apache is using), I am still getting the same exact error when trying to log in. 

From what I can tell from looking at the differences between Django with uWSGI vs Django with Apache + mod_uwsgi on the page you linked, I am serving the wsgi.py correctly with Apache (which was basically just setting an Alias for the static files, WSGIScriptAlias for the wsgi.py to be at the root of the site, and granting wsgi.py access to the files it needed as opposed to everything in the nginx and uwsgi sections in the production instructions) as replacing wsgi.py with a file containing
<pre>def application(env, start_response):
    start_response('200 OK', [('Content-Type','text/html')])
    return [b"Hello World"]</pre>
works as expected. <i>Maybe</i> the issue is related to the middleware in wsgi.py?

I changed wsgi.py back to using fir.config.production. In production.py, I changed the SECRET_KEY and the relevant fields in DATABASES. I have tried logging in to both [sitename] and [sitename]/admin (which I'm sure you know add "login/?next=/" and "login/?next=/admin/" to the ends of the urls) with admin : admin, dev : dev, fir : [password set with IDENTIFIED BY from MySQL], and the [username] : [password] I set up with `./manage.py createsuperuser --settings fir.config.production`. No luck.

**Comment by tomchop** [comment]
I'd be very curios if you could tell us:

* What happens if you run this in dev mode?
* Have you tried the same setup using nginx?

The problem seems to be coming from django's crypto scripts when authenticating, this could be due to problems when reading the database?

**Comment by CJOak** [comment]
If by dev mode you mean taking down Apache and doing `./manage runserver`, I get "You're accessing the development server over HTTPS, but it only supports HTTP." or just times out (pretty sure it's related to firewalls, which I don't think I have control over; would this be relevant?).

I have not tried nginx, no. I might be allowed to try it just to see if Apache is the problem, but....

**Comment by CJOak** [comment]
Well, looks like I got past the error by following this:
http://stackoverflow.com/questions/36967439/django-login-fails-with-valueerror-unknown-reasons
and putting what it says in production.py . Don't know why it works, but I'm glad it does.

**Comment by tomchop** [comment]
Glad the problem was solved, I was running out of ideas. Thanks for the persistence!
