### ISSUE TITLE
Fail to install dependencies

### ISSUE THREAD

**Issue by cameldelamotto** [certsocietegenerale/FIR#133]
Hello
When I tried to install dependencies on my virtual machine (ubuntu 16.04), I get this error:
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-fccwpna9/flup/

All solutions I found on the internet also failed.

**Comment by tomchop** [comment]
Can you please provide a full stack-trace as well as the command line that gave you this error?

**Comment by cameldelamotto** [comment]
(env-FIR) fir@Server-FIR:~/FIR$ pip install -r requirements.txt
Collecting cssselect==0.9.1 (from -r requirements.txt (line 1))
  Using cached cssselect-0.9.1.tar.gz
Collecting dj-database-url==0.4.1 (from -r requirements.txt (line 2))
  Using cached dj-database-url-0.4.1.tar.gz
Collecting Django==1.9.9 (from -r requirements.txt (line 3))
  Using cached Django-1.9.9-py2.py3-none-any.whl
Collecting django-filter==0.14.0 (from -r requirements.txt (line 4))
  Using cached django_filter-0.14.0-py2.py3-none-any.whl
Collecting djangorestframework==3.4.6 (from -r requirements.txt (line 5))
  Using cached djangorestframework-3.4.6-py2.py3-none-any.whl
Collecting flup==1.0.2 (from -r requirements.txt (line 6))
  Using cached flup-1.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-mlfveddd/flup/setup.py", line 2, in <module>
        from ez_setup import use_setuptools
      File "/tmp/pip-build-mlfveddd/flup/ez_setup.py", line 98
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax

    ----------------------------------------
**Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mlfveddd/flup/**

**Comment by tomchop** [comment]
What version of Python are you using?

**Comment by cameldelamotto** [comment]
Python 3.5.2

**Comment by tomchop** [comment]
That might be the problem; flup (probably a requirement for python uwsgi) doesn't seem to be compatible with 3.5.2. Can you try with python 2.7?

**Comment by cameldelamotto** [comment]
I tried with python 2.7.12 but it didn't work.

The error is a little bit different:

**Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wUOMhN/psycopg2/**

**Comment by cameldelamotto** [comment]
I have the following issue

**Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Traceback (most recent call last):
  File "/home/siifir/env-FIR/bin/pip", line 7, in <module>
    from pip import main
  File "/home/siifir/env-FIR/local/lib/python2.7/site-packages/pip/__init__.py", line 2, in <module>
    from __future__ import absolute_import
ImportError: No module named __future__**

**Comment by cameldelamotto** [comment]
I removed the virtual environnement to solve the issue.
I just have a little problem with the script for fir_uwsgi.service:

When I want to start the service and look at his status I get that:

oct. 10 09:47:41 Server-FIR systemd[1]: Started uWSGI instance for FIR.
oct. 10 09:47:41 Server-FIR systemd[1]: fir_uwsgi.service: Main process exited, code=exited, st
oct. 10 09:47:41 Server-FIR systemd[1]: fir_uwsgi.service: Unit entered failed state.
oct. 10 09:47:41 Server-FIR systemd[1]: fir_uwsgi.service: Failed with result 'exit-code'.
oct. 10 09:47:41 Server-FIR systemd[1]: fir_uwsgi.service: Service hold-off time over, scheduli
oct. 10 09:47:41 Server-FIR systemd[1]: Stopped uWSGI instance for FIR.
oct. 10 09:47:41 Server-FIR systemd[1]: fir_uwsgi.service: Start request repeated too quickly.
oct. 10 09:47:41 Server-FIR systemd[1]: Failed to start uWSGI instance for FIR.
oct. 10 09:47:46 Server-FIR systemd[1]: [/etc/systemd/system/fir_uwsgi.service:12] Failed to pa
oct. 10 09:47:46 Server-FIR systemd[1]: [/etc/systemd/system/fir_uwsgi.service:14] Failed to pa

[5]+  Stopped                 sudo systemctl status fir_uwsgi.service

**Comment by gaelmuller** [comment]
Sorry about the delay ... are you still having this issue ?

Could you try running the command directly outside of systemd in order to get more details ?

**Comment by cameldelamoto** [comment]
Yes yes, you can close.
