### ISSUE TITLE
API Connector

### ISSUE THREAD

**Issue by Saycho** [certsocietegenerale/FIR#135]
Hello,

Are there any connectors/API librairies available to interface FIR with specific third party tools or specific format like XML, JSON, CSV ... ?
The idea is to import data directly to  the FIR tool automatically.

Thanks for your support,

FFA

**Comment by weslambert** [comment]
@Saycho ,

You can get an idea of the API FIR has to offer by navigating to https://fir-instance-address/api.

Thanks,
Wes

**Comment by Saycho** [comment]
Hello,

Thanks you very mouche ;)

See ya
FFA
