### ISSUE TITLE
Pulling comment field through API

### ISSUE THREAD

**Issue by weslambert** [certsocietegenerale/FIR#136]
Is there any way to pull the comment field values through the use of the API?  I would like to be able to pull this value so I can determine the delta between when the event/incident was first opened, and when it was first responded to, in order to track response times.  

Thanks!
Wes

**Comment by weslambert** [comment]
I've used HTML scraping with Python and XPath as an alternative, however, it would still be nice to have this exposed through the API, if possible.

**Comment by eth-0** [comment]
We just did this today. Will submit pull request soon :)

**Comment by weslambert** [comment]
@egd-io ,

Just following up...

Would you be able to share how you accomplished this?

Thanks,
Wes

**Comment by DupliciD** [comment]
I just submitted a pull request for this feature. #200

**Comment by Augustin-FL** [comment]
Hello,

This feature has been implemented a while ago. I will close this issue.
