### ISSUE TITLE
Gunicorn unable to locate fir.wsgi

### ISSUE THREAD

**Issue by espressobeanie** [certsocietegenerale/FIR#138]
Good afternoon, 

I followed all the CentOS 7 install instructions but I'm at the end, configuring the gunicorn service and the service won't start because fir.wsgi "is not a valid module". The FIR-users Google Group must be abandoned because it's been two weeks since I requested access from the owner of the group. Any solutions?

**Comment by Ibrahimous** [comment]
Hi !
Just to be sure, have you taken into account the following note (after the configuration step you mentionned):
![image](https://cloud.githubusercontent.com/assets/3440845/20389775/a73138c0-accb-11e6-86c0-d2a4a6e5c5d7.png)

**Comment by espressobeanie** [comment]
Yep. Same error. "fir.wsgi" is not a valid module.

**Comment by espressobeanie** [comment]
I figured it out. Taking the socket part out resolves the issue. I understand the security need for a socket, but on a production server that's limited to localhost, this does not make sense.
