### ISSUE TITLE
Automatically generate numerical identifiers

### ISSUE THREAD

**Issue by PTW-105** [certsocietegenerale/FIR#139]
I would like to see each event or incident be created and have an automatically generated ID number assigned.  At this time, my team is finding it difficult to reference tickets in conversation.  In some cases, we've reverted to inputting identifiers manually, though this is quite cumbersome.

**Comment by tomchop** [comment]
Every event / incident has an ID number assigned to it. By default, it is accessible through the URL (which may not be super user-friendly). To display it in the web UI, pease refer to #120
