### ISSUE TITLE
ImportError on installing

### ISSUE THREAD

**Issue by lanbus** [certsocietegenerale/FIR#141]
Hello,
I installed all, following the production line up.
I use no virtual environment. 
The webpage gives me an internal server error .
When looking at the status of the fir_uwsgi service I see this message : 
nov. 28 14:19:03 ticketingcert uwsgi[7643]: Python main interpreter initialized at 0x1f07f90
nov. 28 14:19:03 ticketingcert uwsgi[7643]: your server socket listen backlog is limited to 100 connections
nov. 28 14:19:03 ticketingcert uwsgi[7643]: your mercy for graceful operations on workers is 60 seconds
nov. 28 14:19:03 ticketingcert uwsgi[7643]: mapped 72768 bytes (71 KB) for 1 cores
nov. 28 14:19:03 ticketingcert uwsgi[7643]: *** Operational MODE: single process ***
nov. 28 14:19:03 ticketingcert uwsgi[7643]: **

> ImportError: Import by filename is not supported.

**
nov. 28 14:19:03 ticketingcert uwsgi[7643]: unable to load app 0 (mountpoint='') (callable not found or import error)
nov. 28 14:19:03 ticketingcert uwsgi[7643]: *** no app loaded. going in full dynamic mode ***
nov. 28 14:19:03 ticketingcert uwsgi[7643]: *** uWSGI is running in multiple interpreter mode ***
nov. 28 14:19:03 ticketingcert uwsgi[7643]: spawned uWSGI worker 1 (and the only) (pid: 7643, cores: 1)

Anyone as an idea of what could be wrong ?
Thanks,

**Comment by tomchop** [comment]
What platform are you using? Can you try running `manage.py runserver` from the root directory and reproduce the error so we can get the full stacktrace?

**Comment by lanbus** [comment]
I am using a debian.
Here is what the command sends : 
No module named hooks for plugins
No module named hooks for artifacts
/usr/local/lib/python2.7/dist-packages/treebeard/admin.py:62: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got django.views.i18n.javascript_catalog). Pass the callable instead.
  {'packages': ('treebeard',)}),

/usr/local/lib/python2.7/dist-packages/treebeard/admin.py:62: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  {'packages': ('treebeard',)}),

System check identified no issues (0 silenced).
November 28, 2016 - 14:30:48
Django version 1.9.9, using settings 'fir.settings'
Starting development server at http://127.0.0.1:8000/

**Comment by tomchop** [comment]
The bug doesn't seem to happen in the dev environment. What version of uwsgi are you using?

**Comment by lanbus** [comment]
I got 2.0.14

**Comment by tomchop** [comment]
The problem seems to be coming from your uwsgi configuration: 

```
nov. 28 14:19:03 ticketingcert uwsgi[7643]: unable to load app 0 (mountpoint='') (callable not found or import error)
nov. 28 14:19:03 ticketingcert uwsgi[7643]: *** no app loaded. going in full dynamic mode ***
nov. 28 14:19:03 ticketingcert uwsgi[7643]: *** uWSGI is running in multiple interpreter mode ***
```

It's having trouble finding the right app. Can you please share your configuration file with us?

**Comment by lanbus** [comment]
Here they are
[Fir.zip](https://github.com/certsocietegenerale/FIR/files/616510/Fir.zip)

**Comment by tomchop** [comment]
Thanks (you might want to change those passwords though). What about the command line you're using to launch uwsgi ?

**Comment by lanbus** [comment]
Yes already did :)
I use the systemd method with that : 



1 [Unit]
  2 Description=uWSGI instance for FIR
  3 After=syslog.target
  4
  5 [Service]
  6 User=www-data
  7 Group=www-data
  8 WorkingDirectory=/opt/FIR/install/
  9 ExecStart=/usr/local/bin/uwsgi --socket /opt/FIR/install/run/fir.sock --chdir /opt/FIR/install/ --module /opt/FIR/fir/wsgi.py
 10 Restart=always
 11 KillSignal=SIGQUIT
 12 Type=Debug
 13 StandardError=syslog
 14 NotifyAccess=All
 15
 16 [Install]
 17 WantedBy=multi-user.target
~
~

**Comment by tomchop** [comment]
The error must come from the `--module` directive. Try using `--module fir.wsgi` instead.

**Comment by lanbus** [comment]
Ok, I tried that but I have no fir.wsgi module.
So now I have : 
"ImportError: No module named fir.wsgi"

I tried looking into the folder but no fir.wsgi was created. That must be the step I missed.

**Comment by tomchop** [comment]
Wrong commit message, sorry. Please tell me if this works for you, otherwise we'll reopen the issue.

**Comment by lanbus** [comment]
I tried, it stills pop the same error.

**Comment by tomchop** [comment]
According to 
```
ExecStart=/usr/local/bin/uwsgi --socket /opt/FIR/install/run/fir.sock --chdir /opt/FIR/install/ --module /opt/FIR/fir/wsgi.py
```
there's a problem with your directories. You should `/opt/FIR/install` should be the base directory of your FIR installation (where you git cloned it). If you cloned int into `/opt/FIR` you should be using

```
ExecStart=/usr/local/bin/uwsgi --socket /opt/FIR/run/fir.sock --chdir /opt/FIR/ --module fir.wsgi
```

**Comment by lanbus** [comment]
This solved this problem. 
I realised I put the same folder in the nginx as well. I corrected it. Now everything starts with no error, but I have a 502 bad gateway error on the webpage. 
Looking into it.
probably something else.

**Comment by lanbus** [comment]
Ok, found it. I still had one bit of /install/ in the nginx.
Thanks a lot
