### ISSUE TITLE
Reporting not working when USE_TZ = True

### ISSUE THREAD

**Issue by benjimons** [certsocietegenerale/FIR#143]
I can get reports for "Yearly" to appear with results but any of the other views, Quarterly and Sandbox are returning no results, the results in the JSON file are also returning nothing at all even though they do have in the Yearly view.

What information do you need to help trouble shoot this?

**Comment by benjimons** [comment]
I built this on two systems to check, one CentOS and one Ubuntu and both the same problem, Yearly works but nothing else seems to in the Stats section

**Comment by benjimons** [comment]
My bad, it seems that if you delete an incident or incident category from the Django Admin section it screws with the reporting. It works on a fresh install if you dont delete any incidents manually

**Comment by benjimons** [comment]
Okay it appears if you change

```
# If you set this to False, Django will not use timezone-aware datetimes.
USE_TZ = False
```

on fir/config/base.py

to `True`.

seems to throw a fit when reporting is done.

**Comment by Augustin-FL** [comment]
Reporting is now working even when `USE_TZ = True` (including for Quarterly and Sandbox views)

I will close this issue since it was resolved a while ago. Feel free to re-open it if needed
