### ISSUE TITLE
Pictures aren't showing when Nginx server is being run

### ISSUE THREAD

**Issue by espressobeanie** [certsocietegenerale/FIR#144]
I don't understand, I get the website and can log in, but none of the images or background is loading. I tried dangerously setting chmod 777 on the /static folder, but that didn't have any effect. The permissions were also www-data:<local user>, so it should have worked. Ideas?

**Comment by josarsepi** [comment]
Are you certain that your NGINX conf is correctly pointing at your static folder?

https://github.com/certsocietegenerale/FIR/wiki/Installation-on-a-production-environment#nginx shows:
`
    location /static/ {
        alias /path/to/your/FIR/install/static/;
    }
`

What other details can you provide:
- Are you running this in Ubuntu 14.04?
- What about virtualenv?
- How are you starting your fir instance?

I don't know your expertise with Django & Nginx so I may be asking you about stuff you already know and have reviewed.  Please don't take offense if you already looked at all this.

**Comment by gaelmuller** [comment]
I'm closing this issue since there was no answer. Do not hesitate to reopen if needed.
