### ISSUE TITLE
Can't figure out how to close incident from API

### ISSUE THREAD

**Issue by eth-0** [certsocietegenerale/FIR#145]
Using this script to try and close an incident from the API, but the status isn't changing. The `incidents` API endpoint's documentation claims that it can close events, how can you accomplish this?

```
import requests
DEFAULT_HEADERS = {'content-type': 'application/json', 'Authorization': 'Token %%TOKEN_HERE%%'}

data = {'id': '20', 'status': 'C', "description": "this is my desciption", "severity": 3, "detection": 2, "subject": "this is the subject", "category": 12}

r = requests.post('http://localhost:8080/api/incidents/', json=data, headers=DEFAULT_HEADERS)

print(r.content)
```

This returns the following:

```
{"id":24,"detection":2,"file_set":[],"date":"2016-12-12T11:55:14.005063","is_starred":false,"subject":"this is the subject","description":"this is my description","severity":3,"is_incident":false,"is_major":false,"status":"C","confidentiality":1,"category":12,"actor":null,"plan":null,"opened_by":2,"concerned_business_lines":[]}'
```

It makes a new event, `24` and sets it's status to `C` rather than editing the status of event `20`.

**Comment by eth-0** [comment]
Looks like this was never implemented judging by the PR. @byt3smith How were you planning on implementing this? I can do it, but I'd like to get your input.

**Comment by eth-0** [comment]
Reached out to @byt3smith. You can accomplish this by using HTTP PUT rather than POST. PUT will invoke the update() function. So in my script above you'd just change `r = requests.post` to `r = requests.put` and it should work!

**Comment by keoni161** [comment]
How did you manage to make PUT work? In my case, PUT is not allowed, even if I added dav_methods PUT; in the location block in nginx.
