### ISSUE TITLE
"No module named treebeard" when updating "Production"

### ISSUE THREAD

**Issue by josarsepi** [certsocietegenerale/FIR#146]
Error when using the update method located at https://github.com/certsocietegenerale/FIR/wiki/Installation-on-a-production-environment#keeping-your-fir-installation-up-to-date

Clearly some major changes occurred with the big update that took place about 15 days ago and as a result I needed to get "treebeard".  Below I show the error details that occurred when I tried to update and how I managed to bring my existing system up to date without losing any data.

sudo ./manage.py migrate --settings fir.config.production
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named treebeard

# BEFORE PROCEEDING BACK EVERYTHING UP

> Really you should have done this before attempting to upgrade at all.

# This is what I have found that fixes it:

$ sudo stop fir
$ sudo service nginx stop
$ cd /somepath/2/FIR/
$ mv fir/config/base.py fir/config/base.py.old

Pull the repo:
$ git pull

Update requirements
$ sudo apt-get install postgresql-server-dev-9.3	# Resolves issues in building pg_config in next step.
$ vim requirements.txt	# Hash (#) out everything butdjango-treebeard==4.0.1 & markdown2==2.3.1.
$ sudo pip install -r requirements.txt

Apply migrations, if any:
$ ./manage.py migrate --settings fir.config.production

Update static files, if necessary:
$ ./manage.py collectstatic --settings fir.config.production

Update the HTML (https://github.com/certsocietegenerale/FIR/pull/131) for more details:
$ ./manage.py migratehtml --settings fir.config.production

Restart the server:
$ sudo start fir
$ sudo service nginx start

I then had to explicitly assign my user account ALL permissions to see all the data.  Many of the tickets were not visible after the upgrade which means some of the permissions have changed.  Take the time to review who has what permissions.

_No data was lost during the creation of this solution._

Am I missing anything?

**Comment by gcrahay** [comment]
The dev and production installation wiki pages should be updated with:

> Update dependencies:

    $ pip install -r requirements.txt

after:

> Get the latest version of the code: / Pull the repo:

    $ git pull

in sections *One pull a day keeps the core-devs away* and *Keeping your FIR installation up-to-date*

**Comment by josarsepi** [comment]
Did you merge yet?  I'm not seeing the updated wiki content.  Otherwise I think this one can be closed.  Thanks!
