### ISSUE TITLE
Installing FIR for Multiple users on Ubuntu (VMware)

### ISSUE THREAD

**Issue by UBUNTUIR** [certsocietegenerale/FIR#149]
I am running Ubuntu 16.04 on VMware 6.0 and would like to install for multiple users. I am of the impression that to do so, I need to be in installing in root. However, the instructions state that I can't run pip using sudo. How do I run it then?

**Comment by gaelmuller** [comment]
FIR is a web application that is always accessible to multiple users.

The instructions state that you should not run pip using sudo **when running inside a virtualenv**. If you are not using a virtualenv, then you should run pip using sudo.
