### ISSUE TITLE
Idea: VERIS fields

### ISSUE THREAD

**Issue by krmaxwell** [certsocietegenerale/FIR#15]
Have you considered adding fields for [VERIS](http://veriscommunity.net/), similar to what [MozDef](http://mozdef.readthedocs.org/en/latest/) has done?

**Comment by tomchop** [comment]
Not at the moment. Wouldn't you be able to do that by changing the default categories shipped with FIR?

**Comment by sroberts** [comment]
As  a setting or configuration this is :+1:. As a default I'm very :-1:.

**Comment by tomchop** [comment]
We're won't be integrating VERIS fields for the time being. Maybe you can use new categories instead of the ones provided by FIR?
