### ISSUE TITLE
Adding a notification plugin

### ISSUE THREAD

**Issue by gcrahay** [certsocietegenerale/FIR#158]
I've created a third-party plugin named [`fir_async`](https://github.com/gcrahay/fir_async_plugin) to send notifications when an incident is created or updated.

These notifications are sent via email and/or XMPP, but new methods can be easily added.

I am planning to add more events:
- Artifact added
- Artifact detached
- Incident status changed
- Incident commented
- ... 

The core `fir_abuse` plugin added the Celery dependency in FIR, so I suggest adding this notification plugin as a core plugin into FIR as `fir_notifications`. 

Would you like me to submit a PR?

**Comment by benjimons** [comment]
+1 to this. I was looking to make something similar, it would be nice to have both "events" and "incidents" individually configurable for notifications.

**Comment by gaelmuller** [comment]
We are always interested on pull requests, especially when they are in a separate plugin that people can chose to install or not.
