### ISSUE TITLE
Production installation page

### ISSUE THREAD

**Issue by krmaxwell** [certsocietegenerale/FIR#16]
Under "Install MySQL", the `apt-get install` line should add the `python-dev` package or the `pip install mysql-python` will fail with an error.

https://github.com/certsocietegenerale/FIR/wiki/Installation-on-a-production-environment

**Comment by krmaxwell** [comment]
Also, I get errors in `/var/log/nginx/error.log` unless I add the following lines to `/etc/nginx/sites-available/fir`:

```
        fastcgi_param SERVER_NAME $server_name;
        fastcgi_param SERVER_PORT $server_port;
        fastcgi_param SERVER_PROTOCOL $server_protocol;
```

**Comment by tomchop** [comment]
We've fixed the documentation issues, thanks. As for the `Bad Request (400)`, have you checked that `ALLOWED_HOSTS` is actually set to whatever hostname you configured in nginx?

**Comment by lliknart** [comment]
the chapter "Create initial data" in https://github.com/certsocietegenerale/FIR/wiki/Installation-on-a-production-environment gives the following url to get the admin panel: http://localhost:8000/admin.

However, we never configure that port. It works fine for me when i use the follwing url:
http://localhost/admin (i.e. port 80)

**Comment by tomchop** [comment]
You're right, probably some copy / paste fail from the `dev` documentation. Fixed.

**Comment by tomchop** [comment]
@krmaxwell : Any updates on this? Did you manage to make it run in production?

**Comment by gaelmuller** [comment]
No updates for a while, so I'll close this issue. Do not hesitate to reopen it if needed.
