### ISSUE TITLE
Installation requires postgresql

### ISSUE THREAD

**Issue by Rolinh** [certsocietegenerale/FIR#162]
Commit 04dbefcf44b0e8433f5894aa31926065b12c6b7b added a dependency to the `psycopg2` module, a PostgreSQL database adapter. This means that PostgreSQL needs to be installed in order to install FIR otherwise the installation of the dependencies with `pip` will simply fail, as we can see an example in issue #133.

Since the user is offered to alternatively use MySQL, this should not be a hard dependency.

**Comment by gaelmuller** [comment]
@byt3smith: could you clarify if this is needed ? It doesn't not seem to be used on the default Heroku deployment.

**Comment by byt3smith** [comment]
Correct, the `psycopg2` library is NOT a hard required dependency and we should remove it. It is only required if you choose to use Postgres as part of your deployment.
