### ISSUE TITLE
API syntax

### ISSUE THREAD

**Issue by eliebilly** [certsocietegenerale/FIR#166]
Hi !

I would have liked to have the API syntax please

**Comment by eliebilly** [comment]
It's very very reactive !

**Comment by josarsepi** [comment]
The API syntax can be found in the application at the bottom of the incidents page with the "RAW DATA" tab selected:

http{s}://yourfirinstance/api/incidents

{
    "detection": null,
    "actor": null,
    "plan": null,
    "date": null,
    "is_starred": false,
    "subject": "",
    "description": "",
    "severity": null,
    "is_incident": false,
    "is_major": false,
    "status": null,
    "confidentiality": null,
    "category": null,
    "concerned_business_lines": []
}

-----

You can do this for users, artifacts, incidents, and files.

http{s}://yourfirinstance/api/users
http{s}://yourfirinstance/api/artifacts
http{s}://yourfirinstance/api/incidents
http{s}://yourfirinstance/api/files

Good Luck!
