### ISSUE TITLE
Issue with open HTML-tags in comments (tested on 770d9a5d2a1438d97121259ba5a1f93146d0093a)

### ISSUE THREAD

**Issue by MagnusMWW** [certsocietegenerale/FIR#169]
Hello!

A colleague of mine found an issue with comments that contains open HTML-tags. Try for example to open a new incident, add a comment containing "<!--". That will not result in the tag being removed, but actually interpreted. This breaks the "action"-part of the line, making it impossible to remove the comment from the application. You can still do it from Django administration under comments though of course.

A more nasty example is to enter something like "<img/onerror=alert(document.cookie) src=" in a comment.

We've tested this on master from today, (770d9a5d2a1438d97121259ba5a1f93146d0093a).

**Comment by MagnusMWW** [comment]
![screenshot-select-2017-01-25-16 09 05_1465x564](https://cloud.githubusercontent.com/assets/9418331/22295860/a99fd912-e318-11e6-82b8-8b282666457d.png)

This screenshot should illustrate more clearly what I'm trying to describe.

**Comment by gaelmuller** [comment]
Fixed in 0e252d08a1d865bdd4138a4764a2c8c8a591801e
