### ISSUE TITLE
Make the Dev FIR install available to a small local LAN

### ISSUE THREAD

**Issue by MACNIO** [certsocietegenerale/FIR#173]
New to this area and I may have missed this in this location but I cant find anything in here that helps with this question: 
I have successfully stood up a DEV install of FIR and can access the web site via the local host it was installed on. I have a small LAN that I would like to use for other users to log in and create/update items on the FIR, but the website is not available to them. how do make it available to local LAN users and not just the local host? in other words; http://localhost:8000 works so I assumed http://X.X.X.X:8000 would work for hosts on the same LAN the FIR server is on where X.X.X.X is the IP of my FIR server.

**Comment by y9mo** [comment]
Hi,

This should point you in the right direction

* [accessing-django-project-in-lan-systems](https://stackoverflow.com/questions/15471173/accessing-django-project-in-lan-systems)
* [django-accessing-localhost-from-any-machine-connected-to-any-network](https://stackoverflow.com/questions/27962547/django-accessing-localhost-from-any-machine-connected-to-any-network)
* [making-django-server-accessible-in-lan](https://stackoverflow.com/questions/22144189/making-django-server-accessible-in-lan)
