### ISSUE TITLE
Fir_Relations

### ISSUE THREAD

**Issue by bjuditt** [certsocietegenerale/FIR#175]
Hello, I was wondering how the fir_relations plugin works. I know it's supposed to be related to the same events but I do not have anything like it. If someone could make a capture, thank you in advance

**Comment by gcrahay** [comment]
If you mention an incident in an incident description or comment, it will appear in the incident sidebar as related.

To mention an incident, as explained in #106, you have to write the incident prefix configured by the setting `INCIDENT_ID_PREFIX` (default: *FID:*) followed by the incident number (example: *FID:10*).

**Comment by bjuditt** [comment]
Ok i understand !!
Thanks thanks thanks !
