### ISSUE TITLE
Fir_Abuse

### ISSUE THREAD

**Issue by bjuditt** [certsocietegenerale/FIR#176]
Hello,

I think I have a problem with the fir_abuse plugin, if I understood correctly, this one must automatically indicate the mail address of reporting when sending mail (or I misunderstood). In short, for me it does not work, my mail remains empty data

Thanks

**Comment by gaelmuller** [comment]
The documentation is now available at https://github.com/certsocietegenerale/FIR/blob/master/fir_abuse/README.md

Do not hesitate to reopen if needed.
