### ISSUE TITLE
User permissions

### ISSUE THREAD

**Issue by lliknart** [certsocietegenerale/FIR#18]
Hi,
I tried to create 2 users to check if I can manage their permissions. I would like that user2 can't modify incidents created by user1 (for example, user2 could add some comments, artefact etc.. but couldn't modify some important information like date / log / artefact etc... added by user1. Only user1 or the "super user" could).
It seems that user with the "incident handler" persmission can do everything: add, edit, delete all objects. 
I check permissions in the admin panel, but after having tried many configuration, i never succeed to have the behavior I expect.
Moreover, when a user does not have the "incident handler" permission but has others permission like "add incident", he can't access to the "Incident page".

Maybe it's not in your inention to handle a such small granularity of permissions. Or maybe i have to check more information about Django / FIR code.

**Comment by gaelmuller** [comment]
Hello,

Current version of FIR doesn't handle this kind of granularity in permissions. Only the "incident handler" permission should be used. There is currently no way to do what you want.

**Comment by lliknart** [comment]
Ok, thanks !
