### ISSUE TITLE
Tagged Release

### ISSUE THREAD

**Issue by reznok** [certsocietegenerale/FIR#185]
Is it possible to get an official tagged release? It would be nice to start utilizing this project, but due to certain requirements, I need a solid release point that I can continually retrieve.

**Comment by gaelmuller** [comment]
I guess this is something that could be done, but would it not be better if you do it yourself ? This way you would have more control.

You would just have to specify a commit hash instead of a tag.

**Comment by Augustin-FL** [comment]
We are now tagging official releases
