### ISSUE TITLE
no module error after git pull and migration. unable to access Fir

### ISSUE THREAD

**Issue by MACNIO** [certsocietegenerale/FIR#187]
running a dev version of FIR and decided to run a git pull for updates today. 
succesfully ran git pull and ./manage.py migration with no errors. 
after starting the fir back up this is displayed on the web page. 

"InvalidTemplateLibrary at /dashboard/
Invalid template library specified. ImportError raised when trying to load 'fir_plugins.templatetags.markdown': No module named bleach
Request Method:	GET
Request URL:	http://192.168.64.131:8000/dashboard/
Django Version:	1.9.9
Exception Type:	InvalidTemplateLibrary
Exception Value:	
Invalid template library specified. ImportError raised when trying to load 'fir_plugins.templatetags.markdown': No module named bleach"

**Comment by gcrahay** [comment]
Duplicate issue, see #182 .

**Comment by MACNIO** [comment]
thank you.
just reviewed it and I have ran the (fir-env)# pip install -r
requirements.txt command.
appears to work for the most part, but getting this error at the end.
Command "python setup.py egg_info" failed with error code 1 in
/tmp/pip-build-zjax0M/html5lib/


CWO "MAC" McAllister

**Comment by gcrahay** [comment]
Could you paste the output of the `pip install -r requirements.txt` command?

**Comment by MACNIO** [comment]
Sure: (keep in mind this is a DEV install of FIR)
(env-FIR) cwomac@ubuntu:~/FIR$ sudo pip install -r requirements.txt 
[sudo] password for cwomac: 
The directory '/home/cwomac/.cache/pip/http' or its parent directory is not owned by the current 

user and the cache has been disabled. Please check the permissions and owner of that directory. If 

executing pip with sudo, you may want sudo's -H flag.
The directory '/home/cwomac/.cache/pip' or its parent directory is not owned by the current user 

and caching wheels has been disabled. check the permissions and owner of that directory. If 

executing pip with sudo, you may want sudo's -H flag.
Collecting cssselect==0.9.1 (from -r requirements.txt (line 1))
Collecting dj-database-url==0.4.1 (from -r requirements.txt (line 2))
Collecting Django==1.9.9 (from -r requirements.txt (line 3))
  Downloading Django-1.9.9-py2.py3-none-any.whl (6.6MB)
    100% |████████████████████████████████| 6.6MB 190kB/s 
Collecting django-filter==0.14.0 (from -r requirements.txt (line 4))
  Downloading django_filter-0.14.0-py2.py3-none-any.whl
Collecting djangorestframework==3.4.6 (from -r requirements.txt (line 5))
  Downloading djangorestframework-3.4.6-py2.py3-none-any.whl (706kB)
    100% |████████████████████████████████| 716kB 1.3MB/s 
Collecting flup==1.0.2 (from -r requirements.txt (line 6))
Collecting gunicorn==19.6.0 (from -r requirements.txt (line 7))
  Downloading gunicorn-19.6.0-py2.py3-none-any.whl (114kB)
    100% |████████████████████████████████| 122kB 1.7MB/s 
Collecting lxml==3.4.2 (from -r requirements.txt (line 8))
Collecting Markdown==2.6.6 (from -r requirements.txt (line 9))
Collecting pymongo==2.8 (from -r requirements.txt (line 10))
Collecting pyquery==1.2.9 (from -r requirements.txt (line 11))
Collecting python-dateutil==2.4.1 (from -r requirements.txt (line 12))
  Downloading python_dateutil-2.4.1-py2.py3-none-any.whl (188kB)
    100% |████████████████████████████████| 194kB 2.8MB/s 
Collecting pytz==2016.7 (from -r requirements.txt (line 13))
  Downloading pytz-2016.7-py2.py3-none-any.whl (480kB)
    100% |████████████████████████████████| 481kB 1.3MB/s 
Collecting six==1.9.0 (from -r requirements.txt (line 14))
  Downloading six-1.9.0-py2.py3-none-any.whl
Collecting whitenoise==3.2.1 (from -r requirements.txt (line 15))
  Downloading whitenoise-3.2.1-py2.py3-none-any.whl
Collecting django-treebeard==4.1.0 (from -r requirements.txt (line 16))
Collecting markdown2==2.3.1 (from -r requirements.txt (line 17))
Collecting bleach==1.5.0 (from -r requirements.txt (line 18))
  Downloading bleach-1.5.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): html5lib!=0.9999,!

=0.99999,<0.99999999,>=0.999 in /usr/lib/python2.7/dist-packages (from bleach==1.5.0->-r 

requirements.txt (line 18))
Installing collected packages: cssselect, dj-database-url, Django, django-filter, 

djangorestframework, flup, gunicorn, lxml, Markdown, pymongo, pyquery, six, python-dateutil, pytz, 

whitenoise, django-treebeard, markdown2, bleach
  Found existing installation: lxml 3.5.0
    Not uninstalling lxml at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: six 1.10.0
    Not uninstalling six at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed Django-1.9.9 Markdown-2.6.6 bleach-1.5.0 cssselect-0.9.1 dj-database-url-

0.4.1 django-filter-0.14.0 django-treebeard-4.1.0 djangorestframework-3.4.6 flup-1.0.2 gunicorn-

19.6.0 lxml-3.4.2 markdown2-2.3.1 pymongo-2.8 pyquery-1.2.9 python-dateutil-2.4.1 pytz-2016.7 six-

1.9.0 whitenoise-3.2.1
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by gcrahay** [comment]
I don't see any error in this output. Do you have an error when running FIR?

**Comment by MACNIO** [comment]
other than the web page error I posted in my intial posting, all I have is the console output i get on the server when the webpage is first hit (see below):

(env-FIR) cwomac@ubuntu:~/FIR$ ./manage.py runserver 0.0.0.0:8000
Performing system checks...

No module named hooks for plugins
No module named hooks for artifacts
No module named hooks for email
No module named hooks for alerting
No module named hooks for todos
No module named hooks for api
System check identified no issues (0 silenced).
March 08, 2017 - 19:49:03
Django version 1.9.9, using settings 'fir.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Internal Server Error: /login/   **###this pops as soon as I try to load the page from a web browser###**
Traceback (most recent call last):
  File "/home/cwomac/env-FIR/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/cwomac/env-FIR/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/cwomac/FIR/incidents/views.py", line 135, in user_login
    return render(request, 'incidents/login.html')
  File "/home/cwomac/env-FIR/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/cwomac/env-FIR/local/lib/python2.7/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/cwomac/env-FIR/local/lib/python2.7/site-packages/django/template/loader.py", line 26, in get_template
    engines = _engine_list(using)
  File "/home/cwomac/env-FIR/local/lib/python2.7/site-packages/django/template/loader.py", line 143, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "/home/cwomac/env-FIR/local/lib/python2.7/site-packages/django/template/utils.py", line 110, in all
    return [self[alias] for alias in self]
  File "/home/cwomac/env-FIR/local/lib/python2.7/site-packages/django/template/utils.py", line 101, in __getitem__
    engine = engine_cls(params)
  File "/home/cwomac/env-FIR/local/lib/python2.7/site-packages/django/template/backends/django.py", line 31, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "/home/cwomac/env-FIR/local/lib/python2.7/site-packages/django/template/backends/django.py", line 49, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "/home/cwomac/env-FIR/local/lib/python2.7/site-packages/django/template/backends/django.py", line 142, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "/home/cwomac/env-FIR/local/lib/python2.7/site-packages/django/template/backends/django.py", line 159, in get_package_libraries
    "trying to load '%s': %s" % (entry[1], e)
InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'fir_plugins.templatetags.markdown': No module named bleach
[08/Mar/2017 19:49:21] "GET /login/?next=/ HTTP/1.1" 500 117746

**Comment by gcrahay** [comment]
In a virtualenv, you must not use `sudo`. I think you must have permissions issues: 
> Please check the permissions and owner of that directory

Can you try (use Ctrl+D to exit):
```
(env-FIR) cwomac@ubuntu:~/FIR$ python manage.py shell
>>> import bleach
```

**Comment by gaelmuller** [comment]
There was no response to the last comment, so I am assuming this fixed it.

If you are still having issues, do not hesitate to reopen.
