### ISSUE TITLE
manage.py migrate - No module named hooks

### ISSUE THREAD

**Issue by seelview89** [certsocietegenerale/FIR#191]
Dear Gents,

After following carefully the dev-install steps while running the ./manage.py migrate I get the following warnings:

**1:No module named hooks for plugins
2:No module named hooks for artifacts
3:No module named hooks for email
4:No module named hooks for alerting
5:No module named hooks for todos
6:No module named hooks for api**

When I run the django server to start the application the same set of warnings are being displayed before the server initialization. In the application I don't see any way to add new artifacts or so and I suppose the problem may come up from hooks... Any reason on how I can get this fixed ?

Thanks,
Silviu

**Comment by gaelmuller** [comment]
These messages can be misleading, so I removed them in 77a76f5fc2ad82d2f8dc05e98031ca6b151b0aeb.

They were just debug messages basically, so they do not explain any feature not working properly.

Artifacts cannot be created manually, they are automatically extracted from the incident description, comments and/or nuggets.

Do not hesitate to reopen if needed.
