### ISSUE TITLE
Custom upload path

### ISSUE THREAD

**Issue by ankitsultania** [certsocietegenerale/FIR#192]
I cannot really find a way to configure my custom upload path. The reason why i need to do this is because i want the artifacts to be uploaded into an encrypted partition. Can you let me know if there is a configuration which i can change to do this?

**Comment by benjimons** [comment]
Couldnt you just make a symbolic link for your uploads directory to elsewhere on disk that is encrypted?

**Comment by gcrahay** [comment]
The most Django-ish way is to set a custom `MEDIA_ROOT` key in your `dev.py` or `production.py` settings file. See https://docs.djangoproject.com/en/1.9/ref/settings/#media-root

**Comment by ankitsultania** [comment]
Thanks for the info!

**Comment by Augustin-FL** [comment]
As mentioned, you can set up a custom upload path by changing `MEDIA_ROOT` in your setting file.
I will close this issue, feel free to re-open it if needed
