### ISSUE TITLE
Issue with sending email alerts

### ISSUE THREAD

**Issue by ankitsultania** [certsocietegenerale/FIR#194]
Hello,

I have set the required params like e EMAIL_HOST EMAIL_PORT EMAIL_HOST_USER and EMAIL_HOST_PASSWORD in my config file.

I am using gmail smtp server and port as 465

When i try to send an email using alert button from an incident. It just stays in sending state before the browser prompts "something went terribly, terribly wrong!" 

Nothing is being logged in errors.log so i am not able to figure out whats going wrong. Help is appreciated.

Thanks in advance

**Comment by kitophe** [comment]
Hi,

This configurations works for GMAIL account.

# SMTP SETTINGS
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = '<your email>'
EMAIL_HOST_PASSWORD = '<your pwd>'
EMAIL_USE_TLS = True

Regards,

**Comment by Augustin-FL** [comment]
As mentionned, the configuration above works for Gmail.
If your google account is having 2FA enabled, then you need to create an [app password](https://myaccount.google.com/apppasswords) and use it in `EMAIL_HOST_PASSWORD`

I will close this issue, feel free to re-open it if needed.
