### ISSUE TITLE
TInyMCE errors in chrome.

### ISSUE THREAD

**Issue by rivetgeek** [certsocietegenerale/FIR#202]
Unable to type into, or select incident description box when using chrome. Works fine with Firefox.

Using chrome Version 58.0.3029.110 (64-bit), the Tinymce plugin bundled with FIR shows errors in console:

Uncaught TypeError: Cannot set property 'disabled' of null
initContentBody @ tinymce.min.js:8
init @ tinymce.min.js:8
(anonymous) @ tinymce.min.js:8
(anonymous) @ tinymce.min.js:4
o @ tinymce.min.js:3
m @ tinymce.min.js:4
(anonymous) @ tinymce.min.js:4
n @ tinymce.min.js:3

(index):1 Uncaught SyntaxError: Unexpected token :
tinymce.min.js:8 Uncaught TypeError: Cannot set property 'disabled' of null
    at N.initContentBody (tinymce.min.js:8)
    at N.init (tinymce.min.js:8)
    at n.<anonymous> (tinymce.min.js:8)
    at Array.<anonymous> (tinymce.min.js:4)
    at o (tinymce.min.js:3)
    at m (tinymce.min.js:4)
    at tinymce.min.js:4
    at HTMLScriptElement.n (tinymce.min.js:3)

(index):1 Uncaught SyntaxError: Unexpected token :

**Comment by Augustin-FL** [comment]
Fixed in https://github.com/certsocietegenerale/FIR/commit/5af81c80613e63b9aac915e49eccf1e5cc0b92f8
