### ISSUE TITLE
Demo website somewhere ?

### ISSUE THREAD

**Issue by GuiGuiSoft** [certsocietegenerale/FIR#207]
Hello,

Is a demo website available to test FIR quickly as an admin ?
I am experiencing various problem to install it quickly (via the dev install procedure or the usage of the dockerfile...)

Regards.

**Comment by gaelmuller** [comment]
There is no demo website unfortunately.

Maybe you can explain the problems you are having with a quick install so that we can help you ?

**Comment by GuiGuiSoft** [comment]
I followed the procedure here : https://github.com/certsocietegenerale/FIR/wiki/Setting-up-a-development-environment
The installation is made on a local VM with NAT and port 8000 redirection.
Finally I launch the server
```
$ ./manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
September 06, 2017 - 18:12:25
Django version 1.9.9, using settings 'fir.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```
So I think all is good but...
When I try to access the website with FF I get an error
![capture](https://user-images.githubusercontent.com/8069239/30122672-93ca8d7c-932f-11e7-9498-a7a32af6bca6.PNG)

**Comment by gaelmuller** [comment]
Not sure if port redirection works with local addresses. Try running the webserver on all your VM's interfaces:

```
./manage.py runserver 0.0.0.0:8000
```

**Comment by GuiGuiSoft** [comment]
It seems to solve my problem. Thank you !
