### ISSUE TITLE
FIR behind CloudFlare looses posts.

### ISSUE THREAD

**Issue by gllaspida** [certsocietegenerale/FIR#210]
If FIR is running behind CloudFlare and the site is on protection (under attack mode for DDOS) and the user takes more time to submit (write and press "Save") a ticket than the threshold after which CloudFlare gives the user a new ID and shows the waiting page etc, the post of the ticket gets lost.

I was able to reproduce the error several times. If the ticket is written fast enough, so that the protection is not triggered the ticket is submitted normally.

I do not know if it is a CloudFlare related error, but it seems that both entities are involved.

**Comment by Augustin-FL** [comment]
Hi,
This is a cloudflare related error. Please increase your rate limiting and retry : https://developers.cloudflare.com/waf/rate-limiting-rules/

I will close this issue, since it is not directly related to FIR. Feel free to re-open it if needed!
