### ISSUE TITLE
fir_notifications missing event notifications

### ISSUE THREAD

**Issue by tuantmb** [certsocietegenerale/FIR#218]
I'm trying to configure fir_notifications for my FIR in production mode but after some configurations, the event notification configurations are missing as bellow:
![event_config_missing](https://user-images.githubusercontent.com/32200691/33551224-49dee6e2-d923-11e7-8192-b485e22bb19d.png)

Do I need to delete all fir_notifications data in database and re-migrate again?

**Comment by gcrahay** [comment]
Check this setting in `production.py` (it should be set to `False`)

```python
# Send 'incident:*' notification events for both Event and Incident if True
NOTIFICATIONS_MERGE_INCIDENTS_AND_EVENTS = True
```

**Comment by tuantmb** [comment]
@gcrahay Thank you! That's my problem! Thanks for your supporting!
