### ISSUE TITLE
Database migration issue

### ISSUE THREAD

**Issue by PlanetRylos** [certsocietegenerale/FIR#225]
While following the Prod install instructions (not using env-FIR) when I start my ./manage.py runserver I get a warning: YOU HAVE 44 UNAPPLIED MIGRATIONS

<img width="1130" alt="screen shot 2018-02-13 at 12 28 43 pm" src="https://user-images.githubusercontent.com/36412221/36171644-0b4e815c-10c9-11e8-85de-a6de3caa2248.png">

If I try to login without running the python manage.py migrate command, I get a NO SUCH TABLE auth_user error.

<img width="865" alt="screen shot 2018-02-13 at 1 30 04 pm" src="https://user-images.githubusercontent.com/36412221/36171861-c7c5b6e8-10c9-11e8-8ddf-299cf841f61c.png">

If I do the migration, it looks like it works but then I can't login with my superuser account that was created. If I check my database, the superuser is there. 

Python 2.7.6
Django 1.11

**Comment by PlanetRylos** [comment]
was poking around and saw this but it didn't help:

python manage.py migrate auth
python manage.py migrate

neither did running the python manage.py migrate script twice. Hmmm....

All I get is:
"wrong username : password
I can break the rules too."

**Comment by Augustin-FL** [comment]
In order to fix this issue you have to :
```
python manage.py makemigrations
python manage.py migrate
```

This issue date from 2018, i'm assuming your problem got resolved since then. I will close this issue, feel free to re-open it if needed
