### ISSUE TITLE
Question on production install

### ISSUE THREAD

**Issue by DigiAngel** [certsocietegenerale/FIR#23]
I will not be using a virtual environment, so after step:
$ git clone https://github.com/<yourhandlehere>/FIR.git

I'm guessing I mv the fir directory to say /var/html/www?

Also, is there a ready this says yourhandle instead of:
https://github.com/certsocietegenerale/FIR.git

Thank you.

**Comment by gaelmuller** [comment]
I have edited the wiki to remove any mention to <yourhandle> in the production installation page. Forking the repo is not mandatory.

The directory in which you are installing FIR is not really important, as long as you are setting your reverse proxy to use the correct path.

**Comment by DigiAngel** [comment]
And there it is...thanks so much for the quick answers.
