### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by XiQshoner** [certsocietegenerale/FIR#232]
Hello Folks,

I am not very great on the Linux command line so please talk to me like a first timer.
Essentially, I have installed the FIR platform to the following path"home/so-ebrown/FIR/fir"
I filled out everything for the/etc/init/fir.conf file as below:
```
description "FIR - Django uWSGI"

start on runlevel [2345]
stop on runlevel [!2345]

setuid www-data
setgid www-data

respawn

exec uwsgi --socket /home/so-ebrown/FIR/fir/run/fir.sock --chdir /home/so-ebrown/FIR/fir --module fir.wsgi

```
However when I run the `sudo start fir` command I get the following error: sudo: start: command not found. 
I also tried to use the systemd instructions however when I run the `sudo service fir_uwsgi start` Nothing seems to happen just directly to a new line. I'm sure there is something that I am doing wrong.

I do have the production.py file @ /home/so-ebrown/FIR/fir/config if it holds any relevance.

Thanks in advance,
Eddie

**Comment by XiQshoner** [comment]
So I scrapped the above install and re-installed using 14.0.4 and making sure I had all the paths correct. The service seems to start now. I am able to browse to the webpage however i am getting a internal server error.

**Comment by gaelmuller** [comment]
Could you output the error that should be present in the `logs/errors.log` file ?

**Comment by Augustin-FL** [comment]
I will close this issue (for inactivity). Feel free to re-open it if needed!
