### ISSUE TITLE
Login screen unavailable with FIR hosted in subdirectory

### ISSUE THREAD

**Issue by p4tpr0** [certsocietegenerale/FIR#234]
I've installed FIR on an existing Apache server, the application seems to work fine (not fully tested), but the login screen fails to load because of a wrong redirection:

My install is available at **/FIR**, but the application redirect non-authenticated users to **/login/?next=/FIR/** instead of **/FIR/login/?next=/FIR/** : 

`$ curl -qLI https://server/FIR 2>/dev/null| egrep '^HTTP|Location|^\s$'
HTTP/1.1 302 Found
Location: /login/?next=/FIR/

HTTP/1.1 404 Not Found

`

Loading https://server/FIR/login/?next=/FIR/ into the browser allows users to log in and use the application.

**Comment by p4tpr0** [comment]
Same goes with the BL choice menu in the stats/quarterly/ page: if my install is hosted in /FIR changing BLs send the browser to https://server/stats/quarterly/<BL> instead of https://server/FIR/stats/quarterly/<BL>.

**Comment by Augustin-FL** [comment]
Hi,

You may be able to host FIR in a directory but you will need to add rewrite rules  (proxy_redirect on Nginx,  ProxyPassMatch & ProxyPassReverse on Apache, etc..) for it to work.

I will close this issue, since this is out of scope of FIR. Feel free to reopen it if you still need help !
