### ISSUE TITLE
Problem with LDAP auth / user profile init

### ISSUE THREAD

**Issue by p4tpr0** [certsocietegenerale/FIR#235]
Hello,

I've successfully installed FIR and plunged in Django Auth LDAP module. My LDAP users can log in: user profile is created with proper flags (is_staff and/or is_active), their token is generated, their connection is logged in the database. But, unfortunately after that, they are sent back to the login screen.

I have to log in as admin to add either "Groups permissions" or "BL + Role" in order for them to be able to enter the application. Once it's done, LDAP users have normal access to the application.

I would like that those permissions to be set at login time, depending on user's groups, but I failed.

Here are my settings: (from production.py)
 91 ####################################                                                                                                                
 92 
 93 import ldap
 94 from django_auth_ldap.config import LDAPSearch, GroupOfNamesType
 95 
 96 AUTH_LDAP_SERVER_URI = "ldaps://ldap.example.com"
 98 AUTH_LDAP_USER_DN_TEMPLATE = "uid=%(user)s,ou=people,dc=example,dc=com"
 99 AUTH_LDAP_USER_ATTR_MAP = {
100     "first_name": "givenName",
101     "last_name": "sn",
102     "email": "mail"
103 }
104 
105 AUTH_LDAP_BIND_AS_AUTHENTICATING_USER = True
106 
107 AUTH_LDAP_USER_FLAGS_BY_GROUP = {
108     "is_active": "cn=X,cn=A,ou=groups,dc=example,dc=com",
109     "is_staff": "cn=Y,cn=A,ou=groups,dc=example,dc=com",
111 }
112 
113 AUTH_LDAP_PROFILE_FLAGS_BY_GROUP = {
114     "report_events": "cn=Y,cn=A,ou=groups,dc=example,dc=com",
115 }
116 
117 # Set up the basic group parameters.
118 AUTH_LDAP_GROUP_SEARCH = LDAPSearch("cn=A,ou=groups,dc=example,dc=com",
119     ldap.SCOPE_SUBTREE, "(objectClass=groupOfNames)"
120 )
121 AUTH_LDAP_GROUP_TYPE = GroupOfNamesType()
122 
123 # Use LDAP group membership to calculate group permissions.
124 AUTH_LDAP_FIND_GROUP_PERMS = True
125 
126 # Cache group memberships for an hour to minimize LDAP traffic
127 AUTH_LDAP_CACHE_GROUPS = True
128 AUTH_LDAP_GROUP_CACHE_TIMEOUT = 3600
129 
130 # AUTH
131 # Authentication and authorization backends
132 AUTHENTICATION_BACKENDS = (
133     'django_auth_ldap.backend.LDAPBackend',
134     'django.contrib.auth.backends.ModelBackend',  # default
135     'incidents.authorization.ObjectPermissionBackend',
136 )

Lines 113-115 I've tried and put some sensible settings so that proper permissions are assigned to newly created profiles, but no luck… I know nothing about Django.

Any help appreciated.

**Comment by Augustin-FL** [comment]
Hello,

Indeed, the Django Auth LDAP module does not support natively binding LDAP groups to django groups with different names.

Some customization is required in order to overcome this:

```
import ldap
from django_auth_ldap.config import LDAPSearch, GroupOfNamesType


AUTH_LDAP_SERVER_URI = "ldaps://ldap.example.com"
AUTH_LDAP_USER_DN_TEMPLATE = "uid=%(user)s,ou=people,dc=example,dc=com"
AUTH_LDAP_USER_ATTR_MAP = {
"first_name": "givenName",
"last_name": "sn",
"email": "mail"
}

# Django LDAP module does not support fetching the LDAP groups of an user when
# AUTH_LDAP_BIND_AS_AUTHENTICATING_USER = True. You need to use a service account
AUTH_LDAP_BIND_DN = "uid=firServiceAccount,ou=serviceAccounts,dc=example,dc=com" 
AUTH_LDAP_BIND_PASSWORD = 'SomeStrongPassword'

AUTH_LDAP_USER_FLAGS_BY_GROUP = {
 "is_active": "cn=X,ou=groups,dc=example,dc=com",
 "is_staff": "cn=Y,ou=groups,dc=example,dc=com",
}

AUTH_LDAP_USER_GROUP_MAP = {
 "Incident handlers": "cn=X,ou=groups,dc=example,dc=com",
 "Incident viewers": "cn=Y,ou=groups,dc=example,dc=com",
}

AUTH_LDAP_GROUP_SEARCH = LDAPSearch("ou=groups,dc=example,dc=com",
       ldap.SCOPE_SUBTREE, "(objectClass=groupOfNames)"
)

class UserAttributeGroupType(GroupOfNamesType):
    def user_groups(self, ldap_user, group_search):
        return [(group.lower(), {}) for group in ldap_user.attrs["memberOf"]]

    def group_name_from_info(self, group_info):
        for possible_group in AUTH_LDAP_USER_GROUP_MAP:
            if group_info[0] == AUTH_LDAP_USER_GROUP_MAP[possible_group].lower():
                return possible_group
        return None

AUTH_LDAP_GROUP_TYPE = UserAttributeGroupType()

# Use LDAP group membership to calculate group permissions.
AUTH_LDAP_FIND_GROUP_PERMS = True

# Cache group memberships for an hour to minimize LDAP traffic
AUTH_LDAP_CACHE_GROUPS = True
AUTH_LDAP_GROUP_CACHE_TIMEOUT = 3600

# AUTH
# Authentication and authorization backends
AUTHENTICATION_BACKENDS = (
'django_auth_ldap.backend.LDAPBackend',
)
```

**Comment by Augustin-FL** [comment]
I will close this issue since a solution was provided. Feel free to reopen it if needed !
