### ISSUE TITLE
DisallowedHost at /

### ISSUE THREAD

**Issue by L3V14TH4N** [certsocietegenerale/FIR#237]
I have this problem. 
![image](https://user-images.githubusercontent.com/6493983/46674501-aa810700-cbb2-11e8-9f4a-758e85d7faeb.png)

But accessing internally (http://127.0.0.1:8000).
![image](https://user-images.githubusercontent.com/6493983/46674618-fb90fb00-cbb2-11e8-983a-1ff739023ca3.png)

in: Dockerfile
`CMD ["runserver", "0.0.0.0:8000"]`

in: /fir/config/base.py
`ALLOWED_HOSTS = ["127.0.0.1", "10.0.97.170"]`

How can I solve this?

**Comment by satyaakam** [comment]
add the following line in FIR/fir/settings.py
ALLOWED_HOSTS=["whateveryour.com", "localhost", "127.0.0.1"]

**Comment by Lehuuminhtri** [comment]
> add the following line in FIR/fir/settings.py
> ALLOWED_HOSTS=["whateveryour.com", "localhost", "127.0.0.1"]

Thank you so much satyaakam!
