### ISSUE TITLE
Install trouble

### ISSUE THREAD

**Issue by DigiAngel** [certsocietegenerale/FIR#24]
Well...I followed everything pretty much to the letter.  I'm greeted with:

Bad Request (400)

When I try anything, so I think this is an nginx issue.  Things I need clarification on:
production.py - ALLOWED_HOSTS = ['localhost'] <- what is this for?

This is the first time I've EVER used nginx, so I'm not sure what I need to do.  
in file /etc/nginx/sites-available/fir

I have
server {
    server_name ip.address;

This server is internal and will be accessed by IP.  I'd like to ideally have:

http://server.ip.address/fir

As the link.  I'm getting close, but right now all I get is the Bad Request (400) as above.  Thanks for any help.

**Comment by lliknart** [comment]
For example, if you set
ALLOWED_HOSTS = ['localhost']
then you have to go to http://localhost/admin for your first connection.

In my configuration i have:
production.py:
ALLOWED_HOSTS = ['fir.domain.com']

in /etc/nginx/sites-available/fir:
server_name fir.domain.com;

so I can go to http://fir.domain.com/admin

**Comment by lliknart** [comment]
Hi,

In production.py, you have to add IP address of your server. For example:
ALLOWED_HOSTS = ['localhost', '10.0.0.1']

and in /etc/nginx/sites-available/fir:
server_name 10.0.0.1;

restart nginx then fir.
It works fine for me.

**Comment by DigiAngel** [comment]
That's EXACTLY what I needed...thanks so much working here!
