### ISSUE TITLE
FIR and SIEM

### ISSUE THREAD

**Issue by recosini** [certsocietegenerale/FIR#243]
Hi all,
I've installed  FIR, but in the guide I cannot find information about SIEM.
I mean: How I do sent information from my SIEM to FIR??

**Comment by udgover** [comment]
You have to create a dedicated connector on your SIEM and use FIR API to create incident in FIR

**Comment by certsocietegenerale** [comment]
Hi,

As suggested by udgover, you can use the FIR API to create new incidents.
An example can be found here : https://github.com/certsocietegenerale/FIR/issues/181#issuecomment-281098082

Please create a dedicated connector on your SIEM for sending detected alerts to an SIRP (such as FIR).
