### ISSUE TITLE
Correct settings for fir_threatintel

### ISSUE THREAD

**Issue by vedburtruba** [certsocietegenerale/FIR#248]
Hello!

I have FIR and YETI installed on same machine, proxied via nginx on different ports.

Yeti web ui and api works well (tested with browser and curl). FIR seems to be working as well.

But I cannot connect FIR to YETI. I added API key to user profile on FIR, also added endpoint as 'http://10.0.0.1:8080/api/'. I have Threat Intel tab in Incident but it tells only 'No intelligence available for this incident. Please check your configuration settings.'

Also I checked nginx access logs and found that there is no API requests from FIR, only from my PC (when I tested API).

Could you please tell what is correct settings for FIR-to-YETI integration and how to throubleshoot it?

**Comment by hyperbaba** [comment]
I face the same problem. Watched traffic on the wire and there is no communication from fir to yeti

**Comment by tomchop** [comment]
Uncommenting these lines in Yeti should help

https://github.com/yeti-platform/yeti/blob/f7911cf2e3b6401c49230f93d22f7cff46eeebe9/core/web/api/api.py#L16

**Comment by hyperbaba** [comment]
Thank you, did not know that. Instead i've created an monstrosity in the nginx config to manage the needed headers.

**Comment by Augustin-FL** [comment]
I will close this issue, since it is resolved. 

Feel free to reopen it if needed
