### ISSUE TITLE
Questions and feature request

### ISSUE THREAD

**Issue by DigiAngel** [certsocietegenerale/FIR#25]
So....what's a "Blocked" incident?  And is there a way to get Events to show up in the Dashboard and in the Stats page?  I currently have added just a test Event only which is closed and I don't see it in either of the above.  Thank you.

**Comment by lliknart** [comment]
The "blocked" status can be used when you need more data to continue to investigate. For example when some information are missing to continue (close ?) or when you need a network access to investigate etc...
The close events are only displayed in the Event page, not in Dashboard.

**Comment by DigiAngel** [comment]
Excellent...thank you for the information.
