### ISSUE TITLE
Events tab empty

### ISSUE THREAD

**Issue by Bahia18** [certsocietegenerale/FIR#253]
Hello,

What is the purpose of the Events tab ?
When creating events everything is posted in the incidents tab.

**Comment by gaelmuller** [comment]
It depends on the Event Category. Some categories are automatically "promoted" to Incidents.

**Comment by Bahia18** [comment]
Ok thank you.

**Comment by udgover** [comment]
This issue can be closed based on explanation provided by @gaelmuller
