### ISSUE TITLE
The incident table is  showing as category object 

### ISSUE THREAD

**Issue by AbdullahAsem** [certsocietegenerale/FIR#256]
![image](https://user-images.githubusercontent.com/4209603/87969915-fbfd3c00-ca90-11ea-84e3-cbcd4251e00c.png)
For some reason, I can't see the actual value in the view and admin

**Comment by udgover** [comment]
Can you please describe python and django version? While porting to python3 I encountered this problem which was linked to the overiding of __unicode__ in models which is now replaced by __str__.

**Comment by Augustin-FL** [comment]
As mentionned by udgover, this issue was related to python2 and is now fixed
