### ISSUE TITLE
systemctl status nginx.service

### ISSUE THREAD

**Issue by MElbeshti** [certsocietegenerale/FIR#258]
root@fir:~# systemctl status nginx.service
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: active (running) (Result: exit-code) since Mon 2020-07-27 10:09:05 UTC; 2h 21min ago
     Docs: man:nginx(8)
  Process: 16996 ExecReload=/usr/sbin/nginx -g daemon on; master_process on; -s reload (code=exited, status=1/FAILURE)
  Process: 1264 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
  Process: 946 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
 Main PID: 1281 (nginx)
    Tasks: 5 (limit: 4915)
   CGroup: /system.slice/nginx.service
           ├─1281 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
           ├─1285 nginx: worker process
           ├─1286 nginx: worker process
           ├─1288 nginx: worker process
           └─1290 nginx: worker process

Jul 27 10:09:00 fir systemd[1]: Starting A high performance web server and a reverse proxy server...
Jul 27 10:09:05 fir systemd[1]: Started A high performance web server and a reverse proxy server.
Jul 27 11:46:07 fir systemd[1]: Reloading A high performance web server and a reverse proxy server.
Jul 27 11:46:07 fir nginx[4880]: nginx: [emerg] open() "/home/infosec/FIR/run/uwsgi_params" failed (2: No such file or directory) in /etc/nginx/sites-enabled/fir:10
Jul 27 11:46:07 fir systemd[1]: nginx.service: Control process exited, code=exited status=1
Jul 27 11:46:07 fir systemd[1]: Reload failed for A high performance web server and a reverse proxy server.
Jul 27 12:18:21 fir systemd[1]: Reloading A high performance web server and a reverse proxy server.
Jul 27 12:18:21 fir nginx[16996]: nginx: [emerg] open() "/home/infosec/FIR/run/uwsgi_params" failed (2: No such file or directory) in /etc/nginx/sites-enabled/fir:10
Jul 27 12:18:21 fir systemd[1]: nginx.service: Control process exited, code=exited status=1
Jul 27 12:18:21 fir systemd[1]: Reload failed for A high performance web server and a reverse proxy server.

**Comment by udgover** [comment]
As described in logs, it seems nginx can't locate /home/infosec/FIR/run/uwsgi_params

**Comment by certsocietegenerale** [comment]
Hi,

This indicate you didn't configure nginx properly.

Please follow the install steps described here: https://github.com/certsocietegenerale/FIR/wiki/Installation-on-a-production-environment#nginx
