### ISSUE TITLE
Failed to start uWSGI instance for FIR

### ISSUE THREAD

**Issue by MElbeshti** [certsocietegenerale/FIR#259]
(env-FIR) root@fir:/home/infosec/FIR/run# sudo service fir_uwsgi start
(env-FIR) root@fir:/home/infosec/FIR/run# sudo service fir_uwsgi status
● fir_uwsgi.service - uWSGI instance for FIR
   Loaded: loaded (/etc/systemd/system/fir_uwsgi.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-07-27 16:46:16 UTC; 2s ago
  Process: 16331 ExecStart=/usr/bin/uwsgi --socket /home/infosec/FIR/run/fir.sock --chdir /home/infosec/FIR/ --plugins python --module fir.wsgi (code=exited, status=216/GROUP)
 Main PID: 16331 (code=exited, status=216/GROUP)

Jul 27 16:46:16 fir systemd[1]: fir_uwsgi.service: Service hold-off time over, scheduling restart.
Jul 27 16:46:16 fir systemd[1]: fir_uwsgi.service: Scheduled restart job, restart counter is at 5.
Jul 27 16:46:16 fir systemd[1]: Stopped uWSGI instance for FIR.
Jul 27 16:46:16 fir systemd[1]: fir_uwsgi.service: Start request repeated too quickly.
Jul 27 16:46:16 fir systemd[1]: fir_uwsgi.service: Failed with result 'exit-code'.
Jul 27 16:46:16 fir systemd[1]: Failed to start uWSGI instance for FIR.

**Comment by udgover** [comment]
Can you please share used fir_uwsgi systemd file? Can you also test the following one by changing path accordingly to yours?

`[Unit]
Description=uWSGI instance for FIR
After=syslog.target

[Service]
User=www-data
Group=www-data
WorkingDirectory=/var/www/FIR
ExecStart=/usr/local/bin/uwsgi --socket /var/www/FIR/run/fir.sock --chdir /var/www/FIR --module fir.wsgi --uid www-data --gid www-data --enable-threads --processes 2
Restart=always
KillSignal=SIGQUIT
Type=Debug
StandardError=syslog
NotifyAccess=All

[Install]
WantedBy=multi-user.target
`

**Comment by Augustin-FL** [comment]
Hi

FIR is working correctly with the configuration provided by udgover.

I will close this issue. Feel free to reopen it if needed
