### ISSUE TITLE
Production Install: Superuser Credentials

### ISSUE THREAD

**Issue by chleggett** [certsocietegenerale/FIR#26]
I have probably missed something obvious here, but when I get to the ...

"Point your web browser to http://fir.domain.com/admin/ and log in with the superuser credentials you specified during install."

... step, I don't remember specifying any credentials.

I looked back and the earlier steps and tried the admin:admin credentials that worked in the development install.

Can whatever I missed be better emphasized in the Production Install instructions.

Let me know.

Thanks.

**Comment by tomchop** [comment]
We changed the procedure to:

> Point your web browser to http://fir.domain.com/admin/ and log in with the superuser credentials you specified during install. **If you imported users from the provided fixtures, the default superuser credentials are `admin`:`admin`.**

The credentials "specified during install" is in case you use Django's DB creation commands (e.g. `migrate` or `syncdb`). These commands will create the user tables and ask you to define some super-user credentials.

**Comment by chleggett** [comment]
I looked back at my notes again, and sure enough, I did have a username and password that I created. Mea culpa.
