### ISSUE TITLE
Bad Request using docker image (compose method)

### ISSUE THREAD

**Issue by riskynacho** [certsocietegenerale/FIR#268]
Just tried the docker files you shared in the docker directory, when it comes up, I try to access it via ip address and a hostname I gave it, it returns - Bad Request (400).

**Comment by rafaeldrs** [comment]
Same here. I just did some digging and found that "fir" image (the one that is built from the Dockerfile) has some errors. After the container with the fir image fails, fir_web container fails too, and so it's inaccessible.

**Comment by Augustin-FL** [comment]
Hi there,

I'm assuming that's due to the Django version. some `import` and functions have been deprecated on the current version. this cause the fir image to fail at runtime

I made a pull request for fixing this : https://github.com/certsocietegenerale/FIR/pull/272

**Comment by certsocietegenerale** [comment]
Hello,

Sorry for the delay. The PR has been merged, could you confirm the issue is fixed now?

**Comment by rafaeldrs** [comment]
> Hello,
> 
> Sorry for the delay. The PR has been merged, could you confirm the issue is fixed now?

Yes, it is solved now. Thanks!
