### ISSUE TITLE
能不能靠谱点？换了2个包都不能直接顺利docker-compose build & up，不是这个错误就、是那个错误，没测试过吗？最新的commit，up后有 ModuleNotFoundError: No module named 'abuse_finder'错误

### ISSUE THREAD

**Issue by flash-kk** [certsocietegenerale/FIR#274]

**Comment by Augustin-FL** [comment]
Hi,

The docker build is working well.
`abuse_finder` is a module made by @certsocietegenerale : https://github.com/certsocietegenerale/abuse_finder.git

This module is present in [requirements.txt](https://github.com/certsocietegenerale/FIR/blob/master/fir_artifacts_enrichment/requirements.txt
) of a fir module...And requirements [are being installed](https://github.com/certsocietegenerale/FIR/blob/master/docker/Dockerfile#L15) when building the Dockerfile.

One possibility: you performed your `docker-compose build` without proper access to the internet ? If so, please retry in a non-isolated environment.

**Comment by certsocietegenerale** [comment]
Hello,

Can we close this issue?
