### ISSUE TITLE
Feature Request: Incident ID field

### ISSUE THREAD

**Issue by robsmallridge** [certsocietegenerale/FIR#28]
Hello, I notice in the URL that there is an incident/event ID. However this is not displayed on the ticket or the list of incidents/events. for deploying this in a SOC where there are lots of events and incidents it would be useful to search via an incident/event ID 

Thanks

**Comment by lliknart** [comment]
There is a closed issue about it
https://github.com/certsocietegenerale/FIR/issues/14

I take the opportunity of this issue to ask if the code added by gcrahay (about ID display) will be merged in the master branch or not.

TY

**Comment by robsmallridge** [comment]
Thanks!

**Comment by gaelmuller** [comment]
The feature has been merged in master.
