### ISSUE TITLE
Error on building using docker compose (cannot import name 'ugettext_lazy' from 'django.utils.translation')

### ISSUE THREAD

**Issue by dante-asriel-price** [certsocietegenerale/FIR#287]
Trying to stand up FIR on Ubuntu 22.04 and when it gets to app/incidents/models.py I get the error shown below 
File "/app/incidents/models.py", line 8, in <module>
from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/app/venv/lib/python3.8/site-packages/django/utils/translation/__init__.py)

EDIT: I downloaded the latest release from the github page

**Comment by Augustin-FL** [comment]
Hi,

Seems that you are NOT using the latest version

`ugettext_lazy` was removed from `incidents/models.py, line 8` during [January 2022](https://github.com/certsocietegenerale/FIR/commit/e8eabb8d5e655b0dffc070daceeeb182d0c33a68#diff-5a4e5a2fb4407ab2ee1bc7b2e69ebd825769408090477e0abbf0a811000f58f6R6)

Could you please try to get the latest version and see if it works?

**Comment by Augustin-FL** [comment]
Should be good  now.  Could you download the latest release and retry?

**Comment by Augustin-FL** [comment]
I will close this issue. Feel free to reopen it if needed
