### ISSUE TITLE
Removing business lines causes traceback

### ISSUE THREAD

**Issue by brad-accuvant** [certsocietegenerale/FIR#29]
When trying to remove business lines via the admin page, a traceback occurs with the following error:
no such table: incidents_recipienttemplate

**Comment by tomchop** [comment]
We are unable to reproduce the problem. Have you used `migrate` on the `fir_alerting` plugin?

**Comment by brad-accuvant** [comment]
Very sorry, you're correct!  I had chalked up migrate not working to something else, but it was due to an incorrect install on my part.
