### ISSUE TITLE
Installation on SecurityOnion 

### ISSUE THREAD

**Issue by xSunShine** [certsocietegenerale/FIR#290]
Hello,

i manged to install FIR but i can't access it,i installed SecurityOnion in distributed mode and installed FIR on manager node,i changed hosts file on my machine and i still can't access FIR.My installation is all in local network.So it is not exposed to internet so i can not access with domain name which i provided. Would appreciate any help.
I followed this guide https://docs.securityonion.net/en/2.3/fir.html 

Thank you

**Comment by Augustin-FL** [comment]
Hi

SecurityOnion removed FIR support from its platform

I will close this issue. Feel free to reopen it if needed
