### ISSUE TITLE
Not able to successfully install on Ubuntu 22.04

### ISSUE THREAD

**Issue by jray1987** [certsocietegenerale/FIR#292]
I have a lot of errors trying to get this installed on Ubuntu22.04
![image](https://user-images.githubusercontent.com/129539006/229198093-971094b9-c145-4034-95e4-4e6d33ef90c4.png)

**Comment by Augustin-FL** [comment]
Hi,

To my understanding this issue has been fixed in 2022 :
https://github.com/certsocietegenerale/FIR/commit/c5835db5994b9beee794544880b2a263b497fca7

Could you get the last FIR  source code (from github) and tell me if it is still not working?

**Comment by Augustin-FL** [comment]
Hi

I will close this issue. Feel free to reopen it if needed
