### ISSUE TITLE
Is the he project active ?

### ISSUE THREAD

**Issue by millecentdix** [certsocietegenerale/FIR#293]
Hi,
There is no new commit since october 2022, so my question is simple, is the project still active ?

**Comment by Augustin-FL** [comment]
Hi,

Yes the project is still active. 
There is no new commit since few months because FIR is currently working well as is 😃 If you have new feature ideas feel free to suggest them or to make a pull request for them

**Comment by millecentdix** [comment]
I am happy to read that.
Infortunaly, I'm not a dev, but I have suggestions on Dockerfile ou docker-compose in link of my usage.
My usage of FIR is in standalone on my laptop for tracking my security activity for my organization, I'm the unique user at this time.

**Comment by millecentdix** [comment]
I know that and use it as describe.
For exemple, upload of files in FIR with the nginx conf is not possible without adding the line `client_max_body_size 5M;`.
I can make a PR if you want.

**Comment by Augustin-FL** [comment]
Yes, you can

You may also customize directly the docker instance on your own servers

**Comment by Augustin-FL** [comment]
Hi,
I will close this issue, feel free to reopen it if needed
