### ISSUE TITLE
fir_notifications in dockerized application

### ISSUE THREAD

**Issue by detvan** [certsocietegenerale/FIR#310]
#Hello,

first of all i would like to thank you for a nice project.

We are testing FIR in dockerized environment with following commands:
```
git clone https://github.com/certsocietegenerale/FIR.git
cd FIR/docker
docker-compose build
docker-compose up -d`
```

We follow instructions https://github.com/certsocietegenerale/FIR/wiki/Plugins so my config file fir/config/installed_apps.txt contains
```
fir_api
fir_alerting
fir_todos
fir_nuggets
fir_threatintel
fir_artifacts_enrichment
fir_abuse
fir_notifications
```
Please could you advise, how to follow https://github.com/certsocietegenerale/FIR/blob/master/fir_notifications/README.md or enable fir_notifications in dockerized FIR.

Thank you very much in advance

**Comment by Augustin-FL** [comment]
Hello @detvan,

I'm assuming you would like to send emails when specific actions happen (incident creation, etc)

If that's what you want, you need to: 
- Add the module `fir_notifications` to `installed_apps.txt`
- Make sure each user has an email registered in its profile.
- Make sure each user is subscribed to notifications. This can be set by each user in their profile page (`https://yourFirInstance/user/profile`)
- Configure an email template for each action. This can be set in django admin panel (`https://yourFirInstance/admin/fir_notifications/notificationtemplate/`). 

In addition, the module had some issues, I submitted a PR to fix it (and enable it by default)

If you want to test it, you can execute the following commands:

```
git clone https://github.com/Augustin-FL/FIR.git
cd FIR
git checkout enable_fir_notifications
cd docker
docker compose up --build
```

**Comment by detvan** [comment]
it works! @Augustin-FL, thanks a million
