### ISSUE TITLE
Sending alerts via mail

### ISSUE THREAD

**Issue by nullprobe** [certsocietegenerale/FIR#32]
I'm having an issue with sending mails with FIR. I put my smtp server and port in the production.py but when I try to send a mail with the web interface it remains stuck at "Sending..." after I click the "Send email" button.

**Comment by tomchop** [comment]
Could you please post your log file so that we can help you? If you followed the production tutorial, you should have it in `logs/errors.log`

**Comment by nullprobe** [comment]
The thing is that there are no errors showing up in logs/errors.log...

**Comment by tomchop** [comment]
What browser are you using? Can you provide us the JSON response you get from the server when clicking on the button?

**Comment by nullprobe** [comment]
My bad, seems like there was a firewall port that was closed. Thanks for the quick replies anyway!
