### ISSUE TITLE
Properly keeping production FIR up to date

### ISSUE THREAD

**Issue by DigiAngel** [certsocietegenerale/FIR#35]
Topic says it...I followed the production install instructions and it's been working great.  How do I keep that install up to date?  Thank you.

**Comment by nullprobe** [comment]
Check the bottom of the installation page : 

https://github.com/certsocietegenerale/FIR/wiki/Installation-on-a-production-environment#keeping-your-fir-installation-up-to-date

**Comment by DigiAngel** [comment]
Well I gave that a shot...this is what I get:
~~~
[09:05:33 scanner:/usr/share/nginx/html/FIR$] sudo git pull
remote: Counting objects: 125, done.
remote: Total 125 (delta 66), reused 66 (delta 66), pack-reused 59
Receiving objects: 100% (125/125), 23.94 KiB | 0 bytes/s, done.
Resolving deltas: 100% (77/77), completed with 33 local objects.
From https://github.com/certsocietegenerale/FIR
   c3c04dd..8694c10  master     -> origin/master
Updating c3c04dd..8694c10
error: Your local changes to the following files would be overwritten by merge:
        fir/config/base.py
Please, commit your changes or stash them before you can merge.
Aborting
~~~

I don't think I've modified that base.py file.

**Comment by nullprobe** [comment]
There's probably a changed file anyways, just stash it with 

    git stash

**Comment by DigiAngel** [comment]
That worked...thank you much.
