### ISSUE TITLE
Feature Request: Create Events without logging in

### ISSUE THREAD

**Issue by alas2708** [certsocietegenerale/FIR#37]
Hi,

would it be possible to add the possibility for anyone to create Events (by filling in a basic form with certain mandatory fields) without having an account on the tool?
The idea is that anyone should be able to report security events, that after review, are escalated to incidents or not...

**Comment by tomchop** [comment]
This idea wasn't originally on our roadmap: we'd rather keep the interface accessible to registered users only. This might change once the API is implemented. An API key will still be needed, but there could be a way to create events without having a proper account on the system. We'll keep you posted.

**Comment by erturpin** [comment]
Perhaps you could expose a method in /incidents/views.py that presents an event form that has certain fields forced to particular values (for example, status of "unverified" or something similar).

This view could be anonymously accessible from an authentication perspective.

**Comment by reynas** [comment]
Hey

Is the API usable for generating events yet? If not, this is a definitely a big feature request!

thanks!

**Comment by tomchop** [comment]
Yes, you can use the API for generating events (you need an auth token first). We still need to write a full documentation for it but in the meantime you can check out the root API URL (`/api/`), which displays an interface in which you can play around with stuff. 

Email binding is still on our ToDo list.

**Comment by tomchop** [comment]
Closing this since using a special account + the API solves the issue.
