### ISSUE TITLE
Feature Request: Event system for integration patterns

### ISSUE THREAD

**Issue by Zenithar** [certsocietegenerale/FIR#38]
Hello,

It would be great to have an integration bus (a broker) or webhooks that broadcast events from system such as :
- Incident created, updated, deleted, closed, etc.

I'm currently working on a wallboard for all product we use, and integration is the key problem to all products.

Not necessarily a complex broker (RabbitMQ) but something light (Redis PUB/SUB, 0MQ, Webhooks).

Regards.

**Comment by tomchop** [comment]
This requires some work on our part (unless Django provides an option to quickly deploy it) and it is unfortunately not on our list of top priorities for the moment.

**Comment by gaelmuller** [comment]
Closed in favor of #161
