### ISSUE TITLE
Feature Request: Template Tasks list by incident type

### ISSUE THREAD

**Issue by trolldbois** [certsocietegenerale/FIR#39]
For each incident type, the list of tasks to be done and who should do it in a team are the very similar from one incident to the next one.
Each incident type should have a template that contains the basic list of tasks that an organization follows to handle an incident (based on NIST maybe ?)

**Comment by tomchop** [comment]
That could be interesting to implement. It would be interesting to let the users chose which todos to set for each incident type.

**Comment by sroberts** [comment]
:+1: Very interested in this. It also makes it far easier to have non-security (like support teams) work through these processes with security oversight.

**Comment by erturpin** [comment]
Also interested in this!

**Comment by keoni161** [comment]
Very interested in this as well.

**Comment by crapwarelabs** [comment]
+1 on this enhancement request

**Comment by gaelmuller** [comment]
Apparently I forgot to close this issue. This feature was implemented as "Todo Templates". Documentation is available in `fir_todo`'s README.

https://github.com/certsocietegenerale/FIR/blob/master/fir_todos/README.md
