### ISSUE TITLE
Error(s) on Setting up a development environment steps

### ISSUE THREAD

**Issue by hiddenillusion** [certsocietegenerale/FIR#40]
1.  Under the step _Fork the GitHub repo and clone it_ the instructions state to:
	```
	$ git clone https://github.com/<yourhandlehere>/FIR.git
	```
	which should read:
	```
	$ git clone https://github.com/certsocietegenerale/FIR.git
	```
	^ This is also how it's stated within https://github.com/certsocietegenerale/FIR/wiki/Installation-on-a-production-environment

2.  Under the step _Create the tables in the database_ the instructions state to:
	```
	$ ./manage.py syncdb --noinput
	$ ./manage.py migrate
	```
	however, running `migrate` prior to/without `makemigrations` resulted in the following error:
	```
	(env-FIR)hithere@yourhouse:~/Desktop/FIR# ./manage.py migrate
	Operations to perform:
	  Synchronize unmigrated apps: fir_alerting
	  Apply all migrations: fir_nuggets, fir_artifacts, sessions, admin, sites, auth, fir_todos, contenttypes, incidents
	Synchronizing apps without migrations:
	  Creating tables...
	  Installing custom SQL...
	  Installing indexes...
	Running migrations:
	  No migrations to apply.
	  Your models have changes that are not yet reflected in a migration, and so won't be applied.
	  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
	```

**Comment by gaelmuller** [comment]
Thank you for your report. I just added the missing migration to fix your second point.

The first point is actually not a mistake. When you are setting up a development environment, you should start by forking the repository, so that you can commit your changes to your repository, and then submit pull requests.
