### ISSUE TITLE
Unicode filenames are not handled properly

### ISSUE THREAD

**Issue by jipegit** [certsocietegenerale/FIR#42]
Unicode filenames are not handled properly in attached files and Todo.

![unicode1](https://cloud.githubusercontent.com/assets/4620502/9836650/84362ae0-5a21-11e5-86e3-20de06cf2391.png)
![unicode2](https://cloud.githubusercontent.com/assets/4620502/9836651/843989f6-5a21-11e5-858f-e99e705aa24c.png)

**Comment by mthlvt** [comment]
Unicode support seems to be a general issue since the DB charset is set to 'latin1_...'

It can be fixed by replacing 'latin1_...' charset with 'utf8_general_ci' in all table fields where characters are not handled properly.

see: https://codex.wordpress.org/Converting_Database_Character_Sets
