### ISSUE TITLE
Feature request: Ability to export stats

### ISSUE THREAD

**Issue by keoni161** [certsocietegenerale/FIR#44]
Good morning,
It would be most useful if stats results (mainly the list of matching incidents) could be exported as an excel/csv/pdf or any other format file.
Also if this option would be available in the incidents/events tab.
If not possible/feasible I will try to implement it myself.
Thank you very much for this excellent solution.
Claudiu

**Comment by tomchop** [comment]
It can be easily exported in CSV (which is basically text). Excel shouldn't be too hard since there are many libraries that do that already. PDF, on the other hand, can have unpredictable results. We're gonna focus on the CSV aspect for now, thanks for the suggestion!

**Comment by keoni161** [comment]
Thank you very much!

**Comment by benjimons** [comment]
Any update on this? Even just dumping the caes to CSV for particular dates would be super useful

**Comment by tomchop** [comment]
I'll see if I can push this today or tomorrow. @benjimons, which stats page were you thinking of?

**Comment by benjimons** [comment]
the sandbox page is probably best, even if we can jsut dump the incidents table between specific dates would be a good start
