### ISSUE TITLE
Bad Request (400) after installing FIR

### ISSUE THREAD

**Issue by ereuven** [certsocietegenerale/FIR#46]
I followed the instructions in the production installation part, and when I'm trying to access the webpage I getting Bad Request (400) error. No clues in Nginx log files.

**Comment by tomchop** [comment]
Thanks for bringing this up. I'll try to reproduce on my end and let you know what's up.

**Comment by ereuven** [comment]
Thank you. I've installed it directly, without using virtualenv.

**Comment by spcampbell** [comment]
I got the same thing but remedied it and I unfortunately do not remember exactly what fixed it. I am fairly sure that it was a path in one of the config files. Look them over carefully, especially the FCGI configuration. You'll see some places where it has paths like: /path/to/your/fir/install/ You need to modify all of these locations to the correct path. These are not clearly outlined in the text of the instructions but will be obvious when you look for them.

The other thing I messed with was the hostname but I don't think that was the source of the 400 error. If you fix all the paths and still get the error, reply here and we'll check some other things.

**Comment by ereuven** [comment]
OK, thanks to **spcampbell** I managed to solve it.
I did not find another place in the configuration files where I forget to change the path (so probably the explanations in the wiki are good).
The problem was in **production.py, line 9**. It defines the allowed hosts (by default some example domain). I changed it to: **ALLOWED_HOSTS = ['127.0.0.1','localhosts']** and then it worked.

Thank you all.
I think you should add this issue to the instructions on the wiki page. And maybe even change the default to localhost, because it using FCGI and reverse proxy it doesn't have to listen to remote connections.

**Comment by tomchop** [comment]
Thanks a lot for your feedback. Are you sure it's `localhosts`, with an `s`? Or is it just a typo?
In any case, we'll add both `127.0.0.1` and `localhost` to the default `ALLOWED_HOSTS` so that it's more clear to future users.

**Comment by ereuven** [comment]
My mistake, it's **localhost** without s

**Comment by spcampbell** [comment]
FYI I went back and tested to see what it was that fixed my 400 errors. I actually had to put the ip address of the server in the ALLOWED_HOSTS setting. Localhost or 127.0.0.1 did not allow it to work.

**Comment by tomchop** [comment]
Yes, AFAIU the `ALLOWED_HOSTS` directive in Django specifies which vhosts the Django service should be answering requests to. This needs to be adjusted according to your deployment scheme - we'll specify it in the wiki. Thank you all for your comments.

**Comment by Waseem-farooqui** [comment]
I want to see the django interface at public IP what should I do for it.
I did following steps but failed.
1. In **production.py** I have added `'0.0.0.0'`  in **ALLOWED_HOSTS**
2. In **/etc/init/fir.conf** I changed `host=0.0.0.0 port=8000` #Some How Default Django port
3. In **nginx** configurations added `server_name 0.0.0.0;`
4. In **nginx** `fastcg_pass 127.0.0.1:8000;`
But still I got **404** when accessing the staticip.
Where as I can access it on localhost, Where I am wrong please guide me ?

**Comment by tomchop** [comment]
What hostname are you using to browse to FIR? That's what you need to add to the `ALLOWED_HOSTS` array?

**Comment by Waseem-farooqui** [comment]
I am writing the static_ip that I have assigned to the system in browser.

**Comment by tomchop** [comment]
That value should be the one you add to `ALLOW_HOSTS`

**Comment by Waseem-farooqui** [comment]
I have added `0.0.0.0` which means allow all the hosts.
Why should I add my static_ip say **111.111.111.111** I have added `0.0.0.0` and `localhost` in `ALLOW_HOSTS`.

**Comment by tomchop** [comment]
No, the `ALLOW_HOSTS` field specifies which virtual hosts should the Django app answer requests to, like the virutal hosts in you nginx config.

**Comment by Waseem-farooqui** [comment]
(y) thanks I was thinking from different prospective.

**Comment by ulhaqikram125** [comment]
fir start/running, process 5672..terminal give this message.how to check that FIR is running??

**Comment by tomchop** [comment]
If you followed the instructions you should have an upstart stript, so you can `sudo status fir`.

**Comment by ulhaqikram125** [comment]
i got stuck in FIR installation..please help me to install FIR setup.thanx

*ALLAH HAFIZ*

REGARDS
IKRAM UL HAQ
+923459725318
AL-INAM QURAN ACADEMY <http://www.alinamquranacademy.webs.com>

**Comment by lipeviveros** [comment]
Hi guys,

I am having problems with nginx: I am getting reload failed message! to be able to troubleshoot I need to know:

-can you please show me an example of ALLOW_HOSTS format;
- I cant find install directory under my FIR path.

**Comment by lipeviveros** [comment]
Hi,

this is the error that I am getting in NGINX:

nginx: [emerg] open() "/home/user/FIR/run/uwsgi_params" failed (2: No such file or directory) in /etc/nginx/sites-enabled/fir:10


apparently there is something wrong in  /etc/init/fir.conf: 

this is the output of my file: 

description "FIR - Django uWSGI"

start on runlevel [2345]
stop on runlevel [!2345]

setuid www-data
setgid www-data

respawn

exec uwsgi --socket /home/user/FIR/run/fir.sock --chdir /home/user/FIR/ --module


when I try to reboot the service I get this message:

restart: Unknown instance:


please help.
