### ISSUE TITLE
Searching on text in nuggets

### ISSUE THREAD

**Issue by CSIRTUK** [certsocietegenerale/FIR#47]
Should  it be possible to search on indicators such as IP addresses and domains using the search box at the top of the screen.  This doesn't seem to work for me, although if I go to a case containing the indicator I can search by clicking on it.  

The only field which appears to be searchable from the search box is the title field.

Aside from that I think it's a great system.  Many thanks for making it available.

**Comment by tomchop** [comment]
That's strange. The search bear searches through title, body, and comments. You can even filter by business lines and categories by appending `bl:` or `category:` in front of a word.

Can you please check the raw database content of the comment where the IP isn't found? It might be because some HTML formatting got in between.

**Comment by CSIRTUK** [comment]
Certainly. I'll have a look tomorrow. I didn't use any formatting myself
though. I just typed plain text and I've tried several IPs and domains.
Thanks for the swift response. Love the project. Really useful.
Andy Dove

**Comment by CSIRTUK** [comment]
Hi Thomas,

I've had a look at this again and I continue to get the same issue.  The
program is correctly recognising the indicators and highlighting them as
IPs, Hosts, Hashes etc and it allows me to find other related cases by
clicking on the indicator but it won't find them when I search through the
box at the top.  Any assistance on this would be much appreciated.

Kind regards
Andy Dove

**Comment by tomchop** [comment]
Cool. Are you adding the indicators within the "comments" or "nuggets"? Comments are included in the search, but not nuggets (this behaviour will change soon).

**Comment by CSIRTUK** [comment]
That's the answer and also explains why it was able to find some events this morning where the information was in the comment rather than the nuggets!  Thanks for the clarification.  That's really useful :)

**Comment by benjimons** [comment]
Is this something that is still being worked on? At the moment having to add to both comments and nuggets is less than ideal.

**Comment by CSIRTUK** [comment]
You might want to check out a project called TheHive. It's similar to FIR
but is being actively developed. Very easy to set up and use.
Regards
Andy Dove

**Comment by tomchop** [comment]
This is something that can be expected by the end of next week. Stay tuned!

**Comment by tomchop** [comment]
As promised! Search now automatically includes nuggets raw, description, and interpretation fields. Use the `nugget:` modificator in search to search *exclusively* in nuggets' fields.

**Comment by benjimons** [comment]
Awesome!!! Where is the donate button???
