### ISSUE TITLE
how to make a localized from English into Russian ?

### ISSUE THREAD

**Issue by progreccuz** [certsocietegenerale/FIR#48]
how to make a localized from English into Russian

**Comment by progreccuz** [comment]
how to make a localized from English into Russian

**Comment by tomchop** [comment]
Hi. You need to make a directory `locale/ru/LC_MESSAGES` in your plugin folder or in other `locale` folders already present in FIR. Mimick the behavior of the `django.po` files (have a look at this one here: https://github.com/certsocietegenerale/FIR/blob/master/fir_nuggets/locale/fr/LC_MESSAGES/django.po).

Then, `cd` into the directory contatining the `locale` folder (in this example, it would be `fir_nuggets`) and run the following command:

    $ django-admin.py compilemessages

This will generate a bunch of .mo files that Django will use for translating the UI. This command should also be run in the directories of plugins that support internationalization.

**Comment by tomchop** [comment]
Closing this since the instructions were provided. Don't hesitate to reopen should you need help getting the translation to work.
