### ISSUE TITLE
Delete incident comments

### ISSUE THREAD

**Issue by jlanglai** [certsocietegenerale/FIR#5]
When a user delete all the incident comments, you can't load the incident list.
The graphical interface says : "loading...".

The user only needs to do it for 1 incident among all incidents to get this issue.

No errors are present in the logs.

If you need anything else don't hesitate to ask !

**Comment by tomchop** [comment]
Thanks for reporting the issue. FYI, from our perspective, an incident with no comments at all doesn't make much sense

**Comment by jlanglai** [comment]
Thanks the fix works fine. I agree with you an incident should have at least one comment.

But at least if it happens we still have access to all the incidents.
