### ISSUE TITLE
Question: Listening Interface

### ISSUE THREAD

**Issue by HomeGrownCoder** [certsocietegenerale/FIR#54]
Question

is there anyway to have the Dev install listen on more than the 127.0.0.1:8000 interface? I installed the app on unbuntu server but cant access it from outside of the server,

Firewall has been enabled to allow access to port 8000 from anywhere. Small Lab enviroment

@ubuntu:~$ sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
8000                       ALLOW       Anywhere
22                         ALLOW       Anywhere
8000 (v6)                  ALLOW       Anywhere (v6)
22 (v6)                    ALLOW       Anywhere (v6)

@ubuntu:~$ netstat -ltn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:8000          0.0.0.0:*               LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN

**Comment by gaelmuller** [comment]
Hello,

You can pass a host:port argument to runserver. Il you want it to be
accessible on the LAN, use `./manage.py runserver 0.0.0.0:8000`
Le mar. 19 janv. 2016 à 22:42, HomeGrownCoder <notifications@github.com> a
écrit :

**Comment by HomeGrownCoder** [comment]
Thank you for the quick response
