### ISSUE TITLE
Issues Installing From Wiki Procedure (runfcgi is missing)

### ISSUE THREAD

**Issue by AJSNetworks** [certsocietegenerale/FIR#56]
I am following the wiki installation guide and when I get to the FGCI portion, I configure the fir.config file as per instructions but when I try to run FIR with the "sudo start fir" the process starts but dies immediately. 

I tried to troubleshoot by running the command manually and get this error:
<pre>admin@AJS-FIR:/opt/FIR$ sudo /opt/FIR/manage.py runfcgi --settings fir.config.production daemonize=false protocol=fcgi host=127.0.0.1 port=54584
Unknown command: 'runfcgi'</pre>

Suggesting that runfastcgi is not installed.

Scrolling back through my installation I see these errors which may be related after running: "sudo pip install -r requirements.txt"

<pre>
Compiling /tmp/pip_build_root/django/django/conf/app_template/apps.py ...
  File "/tmp/pip_build_root/django/django/conf/app_template/apps.py", line 1
    {{ unicode_literals }}from django.apps import AppConfig
                             ^
SyntaxError: invalid syntax

Compiling /tmp/pip_build_root/django/django/conf/app_template/models.py ...
  File "/tmp/pip_build_root/django/django/conf/app_template/models.py", line 1
    {{ unicode_literals }}from django.db import models
                             ^
SyntaxError: invalid syntax
</pre>

Other Info: Running clean Ubuntu 14.04 server

Im excited to check this out and I am hoping to get this running to teach my students in my class. Is there a stable OVA floating around?

**Comment by gaelmuller** [comment]
I've updated the production installation docs in order to use uWSGI instead of FastCGI. See https://github.com/certsocietegenerale/FIR/wiki/Installation-on-a-production-environment#uwsgi for all the details.

If your only goal (for now I'm sure :p) is to "check this out", you should use a development environment, since it is way easier to setup (see https://github.com/certsocietegenerale/FIR/wiki/Setting-up-a-development-environment).

Please let us know if this fixes your issue.

**Comment by AJSNetworks** [comment]
Ive got some remote students which is why I wanted to set it up with production on Digital Ocean VPS.

I will try out the production config tonight.

Do you have any demo data that can be loaded in? or Do we need to populate it ourselves?

Thank you for the quick response.

**Comment by gaelmuller** [comment]
We are providing very little sample data in seed_data.json (as specified in the install docs), but it only contains some business lines and labels to get you started, no incidents.

**Comment by gaelmuller** [comment]
Documentation was updated to fix this issue.
