### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by Ibrahimous** [certsocietegenerale/FIR#57]
I've got a very strange issue, since I just can't connect to the FIR dashboard... ("Wrong username/password combination" message).
I had a working install with django 1.7 & the appropriate FIR git repository, thus I could make everything run fine before.

I re-installed django, all python modules, and FIR, and my database from scratch, in a virtual environnement.
I am working with Centos 7 + Nginx + Gunicorn + Django (forwarding communications from nginx to gunicorn through a unix socket, but I doubt this should have any consequence on my current issue).

When I migrated, everything worked fine:
<code>
(env-FIR)<ME>@<mymachine>:[env-FIR]: python manage.py migrate --settings fir.config.production
Operations to perform:
  Apply all migrations: fir_nuggets, fir_alerting, fir_artifacts, sessions, admin, sites, auth, fir_todos, contenttypes, incidents
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  […]
  Applying sites.0002_alter_domain_unique... OK
</code>

I have loaded both incidents/fixtures/seed_data.json & incidents/fixtures/dev_users.json (latter of which isn't mentionned in the production install, by the way^^).
I have created a superuser.

I can see users admin, dev, and my superuser when I connect manually to the database.

I do see the POST infos (whith my credentials being posted, then), but nothing in the logs...

This is a good exercise to track aaall the way the credentials go... but a bit of help would be much appreciated :)

Thx to all, great FIR team !

**Comment by Ibrahimous** [comment]
Ok, thx to tomchop who asked the good questions, it was a fairly simple problem of not having modified wsgi.py when I migrated from django 1.7 to 1.9.

Indeed, gunicorn service is launched with the command:
<code>/path/to/my/env/bin/python /path/to/my/env/bin/gunicorn --workers N --bind unix:/path/to/my/env/fir.sock fir.wsgi:application</code>

... which requires to modify wsgi.py from:
<code>os.environ.setdefault("DJANGO_SETTINGS_MODULE", "fir.settings")</code>
to:
<code>os.environ.setdefault("DJANGO_SETTINGS_MODULE", "fir.config.production")</code>

**Comment by tomchop** [comment]
:+1: Don't hesitate to document everything and we'll add it to the wiki.
