### ISSUE TITLE
Doc for installing FIR in a production environnement with nginx, gunicorn, django 1.9 on centos 7

### ISSUE THREAD

**Issue by Ibrahimous** [certsocietegenerale/FIR#61]
Hi,

As github doesn't seem to provide an easy way for issuing pull requests to wiki, here is the doc I wrote in attachment.
Please don't hesitate to have e correct it if needed.

[fir_doc.zip](https://github.com/certsocietegenerale/FIR/files/104714/fir_doc.zip)

Thx for your work

**Comment by Ibrahimous** [comment]
mdp: fir

**Comment by tomchop** [comment]
[Added](https://github.com/certsocietegenerale/FIR/wiki/Installation-on-CentOS-7). Thanks a lot!

**Comment by Ibrahimous** [comment]
U're welcome (& quick^^ ) !
