### ISSUE TITLE
FIR installation

### ISSUE THREAD

**Issue by ulhaqikram125** [certsocietegenerale/FIR#72]
how to give domain name to fir settings???how to run FIR??

**Comment by gaelmuller** [comment]
Hello,

Please have a look at our documentation. You have two choices:

https://github.com/certsocietegenerale/FIR/wiki/Setting-up-a-development-environment

or

https://github.com/certsocietegenerale/FIR/wiki/Installation-on-a-production-environment

**Comment by ulhaqikram125** [comment]
how i can check that FIR is installed successfully? and how can i run it on
my browser?

*ALLAH HAFIZ*

REGARDS
IKRAM UL HAQ
+923459725318
AL-INAM QURAN ACADEMY <http://www.alinamquranacademy.webs.com>

**Comment by gaelmuller** [comment]
We will not be able to help you if you do not provide any information regarding what you did.

What installation procedure did you follow ? Did you have any error along the way ? Is there something in the documentation that you are trying to do that does not work ?

**Comment by ulhaqikram125** [comment]
i choose Installation on a production environment procedure .but i got
stuck on installing nginx installation..i did not understand following
things
"Make sure you replace( FIR.DOMAIN.COM) with the host you will be using to
host your FIR install. This should match what you specified in the
ALLOWED_HOSTS directive in production.py."..
nginx configuration also fail..please help me..if you have any video for
this please share link..thank you so much

*ALLAH HAFIZ*

REGARDS
IKRAM UL HAQ
+923459725318
AL-INAM QURAN ACADEMY <http://www.alinamquranacademy.webs.com>

**Comment by gaelmuller** [comment]
You need to replace `FIR.DOMAIN.COM` in the provided configuration file with the hostname you will use to access FIR.

For example, is you are installing FIR on a server with IP address `75.98.17.65`, you should use this IP address instead of `FIR.DOMAIN.COM`. If this IP address has a domain name associated with it, use the domain name instead.

**Comment by ulhaqikram125** [comment]
thanks man you are a nice person... I want to study FIR and develop a
system for my company.thanks for help

*ALLAH HAFIZ*

REGARDS
IKRAM UL HAQ
+923459725318
AL-INAM QURAN ACADEMY <http://www.alinamquranacademy.webs.com>
