### ISSUE TITLE
how to open FIR page again

### ISSUE THREAD

**Issue by ulhaqikram125** [certsocietegenerale/FIR#74]
how to open FIR test page again from terminal...which commands are required.??

**Comment by tomchop** [comment]
FIR is a web application, you can't use it from the terminal. Please make sure you go through the documentation before opening issues as most questions are answered there.

**Comment by ulhaqikram125** [comment]
sir i installed and run it at localhost (http://127.0.0.1:8000) perfectly
one time but i want to open it again as admin...how can i do it again??

*ALLAH HAFIZ*

REGARDS
IKRAM UL HAQ
+923459725318
AL-INAM QURAN ACADEMY <http://www.alinamquranacademy.webs.com>

**Comment by tomchop** [comment]
You must log out and log in as admin. Default credentials are admin / admin.

**Comment by ulhaqikram125** [comment]
sir what is CERT,BL ans SOC in FIR??

*ALLAH HAFIZ*

REGARDS
IKRAM UL HAQ
+923459725318
AL-INAM QURAN ACADEMY <http://www.alinamquranacademy.webs.com>
