### ISSUE TITLE
Issue with command GRANT ALL PRIVILEGES ON `fir`.* TO 'fir'@'localhost';

### ISSUE THREAD

**Issue by Catopuss** [certsocietegenerale/FIR#76]
Hello, 

When I go to setup the mysql database and i get to the step GRANT ALL PRIVILEGES ON `fir`.* TO 'fir'@'localhost'; I get the below error. 

ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use ner '`fir`@'localhost' .* TO 'fir'' at line 1 

I've retyped multiple time to verify no typos and I'm confident I'm typing it correctly. 

It's running mysql Ver 14.14. Distib 5.5.47

**Comment by tomchop** [comment]
I just tested, and the command works fine on our side:
```
mysql> GRANT ALL PRIVILEGES ON `fir`.* TO 'fir'@'localhost';
Query OK, 0 rows affected (0.00 sec)

mysql>
```
Are you using backticks around the database name?

**Comment by Catopuss** [comment]
It worked for me after I posted but I had to remove the backticks.

**Comment by tomchop** [comment]
Glad it worked then. Closing.
