### ISSUE TITLE
Attributes Graphs mismatch

### ISSUE THREAD

**Issue by goopiebunz** [certsocietegenerale/FIR#78]
So this is probably user error, but I cant figure out what im doing wrond so I thought I would ask. Im using the attributes page to pull reports and graphs, but the time dates in the graphs appear 8 hours back. The incident lists at the bottom show the correct time however. For example, if an entry was recorded for 9am today, looking at the graph in the attributes shows the bar graph at 1am. Any insight on what im doing wrong?

Thanks

**Comment by tomchop** [comment]
That sounds a lot like a timezone issue. What timezone are you in?

**Comment by gaelmuller** [comment]
Are you still having this issue ? If so, can you provide a screenshot and the time range you selected ?

**Comment by gaelmuller** [comment]
I just pushed a commit that might fix this issue. Could you test it and confirm it this changes anything ?

**Comment by gaelmuller** [comment]
I'm closing this since I think this was fixed. Do not hesitate to reopen if this was not the case.
