### ISSUE TITLE
Question: requirements

### ISSUE THREAD

**Issue by commial** [certsocietegenerale/FIR#8]
Some requirements (`/requirements.txt`) seem unused, such as:
- `pymongo`
- `argparse`
- `lxml`

Did I missed something ?

EDIT: (It seems to be related to #3 )
EDIT2: `pymongo` is used for `bson`, my bad.

**Comment by tomchop** [comment]
IIRC, `argparse` and `lxml` are probably being installed by Django. I agree that if it's the case, they shouldn't be in `requirements.txt`. I'll check.

**Comment by commiaI** [comment]
EDIT3: In almost two years, the problem has been solved
