### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Arkheon** [certsocietegenerale/FIR#80]
Hi !

I used this process : https://github.com/certsocietegenerale/FIR/wiki/Installation-on-a-production-environment to install on a VPS ( OVH )

I encountered this error when i tried to access : 502 Bad Gateway

I checked the nginx error logs and i have this 

2016/03/01 11:37:05 [crit] 16917#0: *122 connect() to unix:///root/FIR/run/fir.sock failed (13: Permission denied) while connecting to upstream, client: xxx.xxx.xxx.xxx, server: xxx.xxx.xxx.xxx, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///root/FIR/run/fir.sock:", host: "xxx.xxx.xxx.xxx", referrer: "http://xxx.xxx.xxx.xxx/admin"

I m novice in nginx and unix system .

Could you help me please ?

Best regards 

Vincent

**Comment by Arkheon** [comment]
2016/03/01 09:43:23 [crit] 16362#0: *1 connect() to unix:///FIR/run/fir.sock failed (2: No such file or directory) while connecting to upstream, client: xxx.xxx.xxx.xxx, server: xxx.xxx.xxx.xxx, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///FIR/run/fir.sock:", host: "xxx.xxx.xxx.xxx", referrer: "http://xxx.xxx.xxx.xxx/FIR"

**Comment by gaelmuller** [comment]
Hello,

Could you please provide the output of the following commands so that we can better help you ?

```
$ cat /etc/init/fir.conf
$ sudo status fir
$ sudo ls -l /root
$ sudo ls -l /root/FIR
$ sudo ls -l /root/FIR/run
```

**Comment by Arkheon** [comment]
`$ cat /etc/init/fir.conf`

```
description "FIR - Django uWSGI"

start on runlevel [2345]
stop on runlevel [!2345]

setuid www-data
setgid www-data

respawn

exec uwsgi --socket /root/FIR/run/fir.sock --chdir /root/FIR/ --module fir.wsgi
```

` sudo status fir`

return nothing...

`$ sudo ls -l /root`

```
total 4
 drwxr-xr-x 16 root root 4096 mars   1 09:00 FIR
```

` sudo ls -l /root/FIR`

```
total 100
drwxr-xr-x  2 root     root  4096 mars   1 08:37 docker
drwxr-xr-x  3 root     root  4096 mars   1 10:57 fir
drwxr-xr-x  6 root     root  4096 mars   1 08:44 fir_alerting
drwxr-xr-x  2 root     root  4096 mars   1 08:37 fir_api
drwxr-xr-x  6 root     root  4096 mars   1 08:44 fir_artifacts
drwxr-xr-x  7 root     root  4096 mars   1 08:44 fir_nuggets
drwxr-xr-x  3 root     root  4096 mars   1 08:44 fir_plugins
drwxr-xr-x  6 root     root  4096 mars   1 08:44 fir_todos
drwxr-xr-x  9 root     root  4096 mars   1 08:44 incidents
-rwxr-xr-x  1 root     root 35113 mars   1 08:37 LICENSE
drwxr-xr-x  2 root     root  4096 mars   1 08:44 logs
-rwxr-xr-x  1 root     root   246 mars   1 08:37 manage.py
-rwxr-xr-x  1 root     root  2047 mars   1 08:37 README.md
-rwxr-xr-x  1 root     root   209 mars   1 08:37 requirements.txt
drwxr-xr-x  2 www-data root  4096 mars   1 13:23 run
drwxr-xr-x 16 root     root  4096 mars   1 08:46 static
drwxr-x---  2 www-data root  4096 mars   1 08:37 uploads
```

`sudo ls -l /root/FIR/run`

```
total 4
srwxr-xr-x 1 root root   0 mars   1 13:23 fir.sock
-rw-r--r-- 1 root root 664 mars   1 09:16 uwsgi_params
```

**Comment by gaelmuller** [comment]
What about:

```
$ sudo stop fir
$ sudo start fir
$ sudo status fir
$ sudo ls -l /
```

**Comment by Arkheon** [comment]
`sudo status fir` 

Return nothing . 

```
sudo ls -l /
total 84
drwxr-xr-x  2 root root  4096 févr. 28 21:14 bin
drwxr-xr-x  3 root root  4096 févr. 28 21:13 boot
drwxr-xr-x 15 root root  3900 févr. 28 21:15 dev
drwxr-xr-x 95 root root  4096 mars   1 10:28 etc
drwxr-xr-x  2 root root  4096 juil.  8  2015 home
lrwxrwxrwx  1 root root    33 juil.  7  2015 initrd.img -> boot/initrd.img-3.19.0-22-generic
drwxr-xr-x 23 root root  4096 mars   1 08:52 lib
drwxr-xr-x  2 root root  4096 juil.  7  2015 lib64
drwx------  2 root root 16384 juil.  7  2015 lost+found
drwxr-xr-x  2 root root  4096 juil.  7  2015 media
drwxr-xr-x  2 root root  4096 avril 17  2015 mnt
drwxr-xr-x  2 root root  4096 juil.  7  2015 opt
dr-xr-xr-x 87 root root     0 févr. 28 21:15 proc
drwx------  6 root root  4096 mars   1 08:37 root
drwxr-xr-x 20 root root   700 mars   1 13:24 run
drwxr-xr-x  2 root root 12288 mars   1 09:05 sbin
drwxr-xr-x  2 root root  4096 juil.  7  2015 srv
dr-xr-xr-x 13 root root     0 févr. 28 21:15 sys
drwxrwxrwt  9 root root  4096 mars   1 13:27 tmp
drwxr-xr-x 10 root root  4096 juil.  7  2015 usr
drwxr-xr-x 13 root root  4096 mars   1 08:35 var
lrwxrwxrwx  1 root root    30 juil.  7  2015 vmlinuz -> boot/vmlinuz-3.19.0-22-generic

```

**Comment by gaelmuller** [comment]
The following commands should fix your issue:

```
$ sudo chmod o+x /root
$ sudo stop fir
$ sudo start fir
```

Please note that this could have security implications, and that `/root` is probably not the best place in your system to install FIR.

**Comment by Arkheon** [comment]
I tried these commands and i still have the problem :/

**Comment by Arkheon** [comment]
re check the log of nginx 

```
2016/03/01 13:59:54 [crit] 17261#0: *171 connect() to unix:///root/FIR/run/fir.sock failed (13: Permission denied) while connecting to upstream, client: IP_CLIENT, server: IP_SERVER, request: "GET /admin HTTP/1.1", upstream: "uwsgi://unix:///root/FIR/run/fir.sock:", host: "IP_SERVER"
2016/03/01 13:59:54 [crit] 17261#0: *171 connect() to unix:///root/FIR/run/fir.sock failed (13: Permission denied) while connecting to upstream, client:  IP_CLIENT, server: IP_SERVER, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///root/FIR/run/fir.sock:", host: "IP_SERVER", referrer: "http://IP_SERVER/admin"

```

**Comment by Arkheon** [comment]
I'll perform a clean install and restart from scratch

**Comment by Arkheon** [comment]
I encountered the same problem again 

My process 

I use debian now
First i create a new user ( not the same mistake with root )

I follow the guide and just before the step of install nginx , i tried to run the fir's daemon with 

`sudo start fir`

I got an error : 

`sudo: start: command not found`

for fix this i install : `apt-get install upstart`

then i tred again to start the daemon 

new error : `start : unable to connect to upstart : failed to connect to socket /com/ubuntu/upstart connexion refusée`

So i look on internet and i found this : https://www.nesono.com/node/368
```

sudo dpkg-divert --local --rename --add /sbin/initctl
ln -s /bin/true /sbin/initctl


```

and now error 502 bad gateway , i think i must do something wrong ...

**Comment by gaelmuller** [comment]
Could you please paste the nging log with the exact error once again with this new install ?

**Comment by Arkheon** [comment]
i tried a reboot of my vps and he's dead :)

this command killed him

sudo dpkg-divert --local --rename --add /sbin/initctl
ln -s /bin/true /sbin/initctl

i ll perform again a a clean install to reproduce the problem , i ll join the log

**Comment by gaelmuller** [comment]
If you can chose what system to use, you should use Ubuntu, in order to be on the same system the docs were built against.

**Comment by Arkheon** [comment]
Ok it's works , i think i understand my mistakes .

I used ubuntu V15.04 and last debian 

They switch from systemd instead of upstart in v15.04.

http://www.pcworld.com/article/2895517/ubuntu-just-switched-to-systemd-the-project-sparking-controversy-throughout-linux.html

That explain why i had this error 
`sudo: start: command not found` 
when i tried to launch
 `sudo start fir`

I will test FIR now :) im happy ! thanks gael for your support ! :+1: 

Maybe it ll be interesting to test ubuntu 15.04 and to check if this theory is correct and update the install procedure :)

Vincent

**Comment by gaelmuller** [comment]
Happy to help

**Comment by 3ldidi94** [comment]
Hi Arkheon,

can you please explain more in details what you did to solve your issue ?

I have exactly the same here :) 

Thanks !

**Comment by Arkheon** [comment]
@3ldidi94 : 

Hi !

My mistake was to use the last version of debian and ubuntu , who use systemd instead of upstart .

To resolve this issue , i used Ubuntu 14.04

**Comment by 3ldidi94** [comment]
@Arkheon : 

Thanks ! 

I have found another solution and it works for me, on an full updated debian jessie.
	
I am running nginx as my present working user that is eldidi. 
By default the user is nginx in nginx.conf. You can find this line at the top of the nginx.conf file :

user nginx;

I have changed this to my current working username :

user  eldidi;

restart the service through /etc/init/fir.conf and it should works ? If you try it can you please leave a feedback ?

thanks
