### ISSUE TITLE
Enhancement: Monthly and Weekly Reports

### ISSUE THREAD

**Issue by dbachletu** [certsocietegenerale/FIR#81]
Request to expand canned FIR reports beyond yearly and quarterly and sandbox stats are not meeting our needs. I would like to copy the yearly report template into weekly and monthly reports with same look and feel and also add events and incidents to a single report.  

If not custom report templates, how about exporting data in csv or similar format to create report using excel or other programs?

**Comment by tomchop** [comment]
Having weekly / monthly reports is not something that we've thought of but it should not be too hard to implement (if it only implies changing the dates and not the look-and-feel of the report). Having a CSV export is something that we can work on though.

**Comment by dbachIetu** [comment]
Can close

**Comment by gaelmuller** [comment]
Ok, closing this. CSV / TSV export has been implemented.
