### ISSUE TITLE
Send automated email on incident creation/update

### ISSUE THREAD

**Issue by aleksf** [certsocietegenerale/FIR#82]
Hi,

I'd like to hear your thoughts about extending fir_alerts to add automated email notifications

It would be cool to expand fir_alerts to be able to send automated emails notifications to configured email group on incident creation/modification/closure. At the moment, the only way of doing this is a modal window that needs to be manually invoked. This is not very practical when dealing with incidents created via API call. 

What are your thoughts/plans on implementing this feature?

**Comment by tomchop** [comment]
This could be interesting (or at least have an API endpoint that triggers the sending of email). We're going to give the API much more love in the following months so I think it's going to be something we're going to implement if it hasn't been done already.
