### ISSUE TITLE
Daemon FIR on debian not working

### ISSUE THREAD

**Issue by Arkheon** [certsocietegenerale/FIR#83]
Hi :)

I have to deploy FIR on a debian .
I follow the doc ( https://github.com/certsocietegenerale/FIR/wiki/Installation-on-a-production-environment ) but in encountered an issue after the creation of : /etc/init/fir.conf

I tried to start the daemon but it did'nt work : 

sudo: start: command not found

how do you start fir in a debian environnement ? 

Thx !

**Comment by tomchop** [comment]
upstart is ubuntu only AFAIK. If you want to start FIR on boot then create a service using your usual methods (maybe this can help? https://www.debian-administration.org/article/28/Making_scripts_run_at_boot_time_with_Debian)

**Comment by Arkheon** [comment]
Thx for the reply , and the documentation !

 but I'm a beginner in unix , and i dont understand how your fir.conf works .

I have no clue how to adapt fir.conf into a service :/

**Comment by tomchop** [comment]
The command that needs to be run at startup is
`uwsgi --socket /path/to/your/FIR/install/run/fir.sock --chdir /path/to/your/FIR/install/ --module fir.wsgi`. Sorry but we can't provide support for other systems.

If you're just trying to test FIR out, we recommend you set-up a development environment instead.
