### ISSUE TITLE
Field IDs for API

### ISSUE THREAD

**Issue by jwilczek** [certsocietegenerale/FIR#86]
When using the API, it looks like you need to know the field IDs prior to using the API.  For example:

"concerned_business_lines": [1]?

Is there a programmatic way to get the IDs ahead of time so I can just use the names in the API like;

"concerned_business_lines": ['Business Line Test']?

If not, I saw an example where someone was requesting '/events/new' and then parsing the resultant HTML to pull out the field IDs.  I could also do this, but it appears as if I cannot access '/events/new' with the Auth Token.

Thanks!

Josh

**Comment by gaelmuller** [comment]
A request using HTTP method "OPTIONS" should give you all the information you need to create incidents, including the list of business lines:

`OPTIONS /api/incidents`

**Comment by jwilczek** [comment]
That does it!  Thanks!

**Comment by jwilczek** [comment]
While your suggestion helped tremendously, it still seems like I'm missing something.  In looking at the data returned by OPTIONS /api/incidents, it seems that there is some overlap in Labels that make programming against the API difficult.

For example, the "actor" label group lists every label defined in our instance of FIR.  However, if I go through the GUI, there is only 1 valid actor label.  This statement applies to multiple fields.

**Comment by gaelmuller** [comment]
This should now be fixed by edd64e523c7a17ed7889c4cace2dfaf80c9bbd64.

**Comment by jwilczek** [comment]
Agreed! Thank you!
