### ISSUE TITLE
Stats>Attributes: Graph shows incorrect month for incidents

### ISSUE THREAD

**Issue by weslambert** [certsocietegenerale/FIR#87]
It looks like when I run a report using Stats>Attributes, the report shows the incorrect month for the incidents (February instead of March).  Am I interpreting this wrong?

![firtimeframe](https://cloud.githubusercontent.com/assets/16829864/14112518/fa3e4aee-f59c-11e5-9cac-4aac9ca221e9.JPG)
![firincidents](https://cloud.githubusercontent.com/assets/16829864/14112520/fc0803e2-f59c-11e5-862d-f2eb8574289d.JPG)
![firgraph1](https://cloud.githubusercontent.com/assets/16829864/14112521/fee2045a-f59c-11e5-8ef1-334c6cf9eac9.JPG)

**Comment by gaelmuller** [comment]
I cannot reproduce. Could you please give me the following information:

  - Your time zone
  - Value of "TIME_ZONE" setting in fir/config/base.py
  - Value of "USE_TZ" setting in fir/config/base.py

**Comment by weslambert** [comment]
My timezone is EST.  The machine's timezone is set to UTC.  TIME_ZONE in base.py is "Europe/Paris".  USE_TZ in base.py is set to "FALSE".

Thanks!
Wes

**Comment by gaelmuller** [comment]
I just pushed a commit that should solve this issue. Could you test it and confirm ?

**Comment by weslambert** [comment]
Thanks!  I've confirmed this fixed the issue.  Also, I couldn't update the wiki, but it may be nice to have a comment here: https://github.com/certsocietegenerale/FIR/wiki/Installation-on-a-production-environment#keeping-your-fir-installation-up-to-date
in regard to running 'manage.py makemigrations' before running './manage.py migrate --settings fir.config.production', as I received an error when I tried to run the 'migrate' before 'makemigrations'.

Thanks,
Wes

**Comment by gaelmuller** [comment]
I don't think you should have to do `makemigrations` when installing. It you did, it probably means that we are missing migrations somewhere. Do you still have the error message that you had ? If so, could you please open a new issue with this message so that we fix it ?

Thank you for reporting this to us.
