### ISSUE TITLE
Dependency when updating FIR with latest fix(es)

### ISSUE THREAD

**Issue by weslambert** [certsocietegenerale/FIR#89]
Please see the following for background info:
https://github.com/certsocietegenerale/FIR/issues/87

I only received this when updating the installation with the latest fix(es). 
Ex. (Steps Perfromed)
git pull --> Success
./manage.py migrate --settings fir.config.production --> ERROR (about `makemigrations`)
./manage.py makemigrations --> Success
./manage.py migrate --settings fir.config.production --> Success
./manage.py collectstatic --settings fir.config.production --> Success
sudo restart fir --> Success

Specific error message for 2nd step in example:

"Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won                                                                                                                                                             't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage                                                                                                                                                             .py migrate' to apply them."

It's not really an issue (I think), just an extra step I had to perform before being able to continue with the previous command.  It just didn't following the order posted in the "Keeping your FIR installation up-to-date" section.  requesting this step be added to the Update section.

Thanks,
Wes

**Comment by gaelmuller** [comment]
Thank you for reporting this issue.

I cannot reproduce. Could you please provide the output of the `git status` command to see if it created a migration ? If so, can you also paste the content of the created migration ?

**Comment by weslambert** [comment]
I didn't receive an error this time, only when applying the previous update.  

Output of git status below:

$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        fir_artifacts/migrations/0005_delete_artifactwhitelistitem.py
        run/
        static/

nothing added to commit but untracked files present (use "git add" to track)

Output of running the commands below:

```
$ sudo ./manage.py migrate --settings fir.config.production[sudo] password for wlambert:
Operations to perform:
  Apply all migrations: authtoken, fir_nuggets, fir_alerting, fir_artifacts, sessions, admin, sites, auth, fir_todos, contenttypes, incidents
Running migrations:
  No migrations to apply.

$ sudo ./manage.py collectstatic --settings fir.config.production

You have requested to collect static files at the destination
location as specified in your settings:

    /home/user/FIR/static

This will overwrite existing files!
Are you sure you want to do this?

yes

0 static files copied to '/home/user/FIR/static', 213 unmodified.
```
Thanks,
Wes
