### ISSUE TITLE
Todo's and Todo List usage?

### ISSUE THREAD

**Issue by crapwarelabs** [certsocietegenerale/FIR#90]
I do not see a way to associate a TODO List with an Incident Template?

I also do not seem to be able to associate TODO's or TODO Lists with an active incident?

How is it supposed to work?

**Comment by gaelmuller** [comment]
There is no way to directly associate a todo list with an incident template. You can however create todo list templates with conditions that will be close to the ones you use in incident templates.

I don't understand the second part of your question. Todo items can only be linked to Incidents. You have to click on 'Add > Todo' to add a Todo Item to an incident.

**Comment by crapwarelabs** [comment]
I have added TODO items in admin panel as well as TODO List.  When I am back in FIR and working an incident I am not able to associate the predefined TODO items or TODO List with that incident.  Should I be able to do so? Or can I only create new TODO items for active incidents?

**Comment by gaelmuller** [comment]
Hello, please have a look at the documentation available on todos:

https://github.com/certsocietegenerale/FIR/blob/master/fir_todos/README.md

Do not hesitate to ask if some things are still unclear.

**Comment by crapwarelabs** [comment]
Thank you yes I found that and am having good success now. Well done!

**Comment by gaelmuller** [comment]
Glad to hear this. Closing this issue.

**Comment by crapwarelabs** [comment]
Hi Gael,

Only one other question is there any way to order the Todo items in a todo list to create a sequence of steps?

_Jayson
