### ISSUE TITLE
Race condition when adding Business Lines

### ISSUE THREAD

**Issue by trolldbois** [certsocietegenerale/FIR#91]
There is a bug in the handling of businessline.
If the user 
1) creates Root parent
2) open a popup to create a Child or two to the root parent
3) change the parent to the Child name

A cycle is created in the parent-child relationship.
The admin menu is then unusable and the server does not serve http response, nor return any error logs.

Symptoms from DB:
mysql> select \* from incidents_businessline;
+----+------------+-----------+
| id | name       | parent_id |
+----+------------+-----------+
|  7 | Corporate  |         6 |
|  6 | Commercial |         6 |
+----+------------+-----------+
2 rows in set (0.00 sec)

**Comment by tomchop** [comment]
We ran into this bug a while ago. Unfortunately I'm not sure how we can enforce that level of control granularity in the Django admin (which is the way things such as categories and business lines are added today).
