### ISSUE TITLE
Add the abiity to search for the user who opened the event

### ISSUE THREAD

**Issue by er587** [certsocietegenerale/FIR#95]
suggest adding the ability to search for the team member who has opened the ticket. 

We use this tool in a tier based security operations team model. The level 1 analyst will open event, investigate, then escalate the incidents to the "incident leader". 

Consider adding the following to the incidents/views.py
```
opened_by = re.search("lvl1:(\S+)", query_string)
        if opened_by:
            q = q & Q(opened_by__username=opened_by.group(1))
            query_string = query_string.replace('lvl1:'+opened_by.group(1), '')
```
Great tool by the way! Thank you

**Comment by gaelmuller** [comment]
This seems like a good change. We won't be using the search keyword 'lvl1' though, as it is too specific to your case. But keyword 'opened_by' would be fine.

Do you want to submit a Pull Request with this change ? If not, we will probably make this change ourselves.

**Comment by gaelmuller** [comment]
Now possible thanks to f29b22b8da1572fd7af123edbe35f264ecd26426
